### ISSUE TITLE
Filter By Phase

### ISSUE THREAD

**Issue by danieljohnbell** [Hoizame/AtlasLootClassic#1]
Hi,

As you know classic will have different phases where different loot will be available, for example: even though molten core is available within phase 1, some items such as the Talisman of Empherial Power is only available from phase 2 onwards. 

There are a number of other items like this, including from dungeons, and it would be nice if there was a filter so that you can look at prospective dungeons to see what can drop for you without having to think if its actually available yet.

https://classic.wowhead.com/items?filter=238;3;2 is the items that become available in p2, and there is a filter where you can select other phases.

**Comment by Hoizame** [comment]
Hey,

adding a phase filter is definitely something I want to add before release of classic and I also have some working concepts with an full item list already.

I also hope we get a more clear definition of what exactly gets added in with each phase but a filter with most items is on my must have list for release.

**Comment by Hoizame** [comment]
I added my concept now. It's WIP and can be enabled in the options.
The display of the phase still needs some love and item->phase need much work I think

**Comment by danieljohnbell** [comment]
Awesome, I'll take a look during the stress/release-test :)

**Comment by danieljohnbell** [comment]
I couldn't get this working during the test, as the minimap icon doesn't seem to appear.

**Comment by Hoizame** [comment]
Did you downloaded it from https://www.curseforge.com/wow/addons/AtlasLootClassic as the github source not contains all libs

**Comment by danieljohnbell** [comment]
I downloaded from source. 

I've downloaded from curseforge now and the minimap icon appears, but how do you enable the phase filtering?

**Comment by Hoizame** [comment]
Shift left klick on minimap button and enable in options

**Comment by danieljohnbell** [comment]
Ah okay, thanks - I didn't know this option existed, I had tried right clicking but not shift + left click.

It looks great, thanks for doing it so quickly!
