### ISSUE TITLE
Is it possible to query atlas loot from another addon to get recipe ItemID from created ItemID?

### ISSUE THREAD

**Issue by aredon** [Hoizame/AtlasLootClassic#101]
Digging through your available functions it appears that it's possible to go recipe->creation spell->created item but I need it to go the other way. I was hoping for something in _G.AtlasLoot.Profession but haven't had any luck so far.

If such a function exists could you point me to where to find it? If not - would you be so kind as to provide it?

**Comment by Hoizame** [comment]
Hey, sure i add `AtlasLoot.Data.Profession.GetCraftSpellForCreatedItem(itemID)` hope that helps :)
Think i will release it tomorrow than as I need to change from Travis to GitHubActions also :D

**Comment by aredon** [comment]
Would it be too much to ask to do GetRecipeFromCreatedItem?

**Comment by Hoizame** [comment]
Nope no problem there is already a function (`Recipe.GetRecipeForSpell(spellID)`) for that but I added it also 
```lua
AtlasLoot.Data.Profession.GetRecipeForCreatedItem(itemID)

function Profession.GetRecipeForCreatedItem(itemID)
    return Recipe.GetRecipeForSpell(Profession.GetCraftSpellForCreatedItem(itemID))
end
```

**Comment by aredon** [comment]
Nice that's wonderful thank you!

**Comment by aredon** [comment]
Is there also a pretty easy way to create an item link from the ID?

**Comment by aredon** [comment]
Sorry - should I not have closed this?
