### ISSUE TITLE
Minimap Button: How to Reset

### ISSUE THREAD

**Issue by Farendil** [Hoizame/AtlasLootClassic#102]
**Is your feature request related to a problem? Please describe.** 
The issue is my AtlasLootClassic minimap button won't reset in the new position I set.  It overlaps another minimap button of another addon.  And the other addon (Bartender4) has no way of resetting that button either,  I will open the same question with that addon as well.

**Describe the solution you'd like**

**Additional context**

**Comment by Hoizame** [comment]
I dont know what exactly you mean but you can:
Hide the minmap button with `/al mmb`
Or reset its position with `/al reset mmb`
