### ISSUE TITLE
I'm not sure if this is a bug

### ISSUE THREAD

**Issue by faffin** [Hoizame/AtlasLootClassic#104]
Phase 6 is out, but the loot in the addon is still locked behind "6"-es. Is there an update that hasn't out yet, or it just can't be found by addon managers?

**Comment by Grookshank** [comment]
You can just replace the line
`local ACTIVE_PHASE = 5`
with
`local ACTIVE_PHASE = 6`
in ContentPhase.lua or use this file.
[ContentPhase.zip](https://github.com/Hoizame/AtlasLootClassic/files/5647193/ContentPhase.zip)
