### ISSUE TITLE
Incorrect Minimum Dungeon Levels

### ISSUE THREAD

**Issue by Cameronza** [Hoizame/AtlasLootClassic#114]
I believe these values to be more accurate, however there seems to be mixed information on the minimum level for Temple of Atal'Hakkar, so I'm unsure on that. 

**Proposed Changes**
Ragefire Chasm: 10 -> 8
Shadowfang Keep: 11 -> 14
Razorfen Kraul: 25 -> 19
Scarlet Monastery: 20 -> 21
Razorfen Downs: 35 -> 25
Zul'Furrak: 39 -> 35
Maraudon: 25 -> 30
Temple of Atal'Hakkar: 45 -> 39? 35?
Blackrock Depths: 42 -> 40
Lower + Upper Blackrock Spire: 48 -> 45
Stratholme: 37 -> 45

**Sources** 
https://progameguides.com/wow/wow-classic-dungeon-levels/
https://vanilla-wow-archive.fandom.com/wiki/Vanilla_WoW_Wiki

**Comment by Laumesis** [comment]
I can confirm that lvl 28 **can't** enter Maraudon.
