### ISSUE TITLE
Razor Fen Downs has nonexistent boss listed Lady Falther'ess doesn't show up till after BC or Cata.  She's not in the Classic Version of the dungeon

### ISSUE THREAD

**Issue by GrantMartin1970** [Hoizame/AtlasLootClassic#115]
**Lua error**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Hoizame** [comment]
She should be a mob from the Scourge Invasions, I moved here into the extra list and marked her

**Comment by anon1231823** [comment]
Yes, Lady Falther'ess is from the Scourge Invasion
