### ISSUE TITLE
Separate classic from TBC?

### ISSUE THREAD

**Issue by anon1231823** [Hoizame/AtlasLootClassic#116]
Seems like it would be a good idea to keep AtlaslootClassic and AtlaslootTBC as two separate projects??

**Comment by Hoizame** [comment]
They are separated packages just the github repo is the same for development

**Comment by anon1231823** [comment]
But in curseforge AtlaslootClassic added localization for TBC bosses

**Comment by Moahawk** [comment]
The files for classic and TBC classic have the same names. So can we not have the classic loot listed in the TBC classic version along with the TBC loot?

**Comment by LightVirus** [comment]
> The files for classic and TBC classic have the same names. So can we not have the classic loot listed in the TBC classic version along with the TBC loot?
> 
> Edit: Please ignore me I have figured out how to see both I apologize.

Could you share how did you do it? :D

**Comment by Hoizame** [comment]
Click on the WoW Symbol between the selection dropdowns

**Comment by LightVirus** [comment]
Oh, a bit hard to see. Thank you!
