### ISSUE TITLE
Display issue: Source text on item tooltips wraps around after prepatch

### ISSUE THREAD

**Issue by almx** [Hoizame/AtlasLootClassic#120]
Version v2.1.0-bc, playing WoW Classic TBC.

When hovering my mouse over an item, the source and drop rate often incorrectly wraps around and into other text. It worked fine on the previous version, before the TBC pre-patch.

Furthermore, the "Show drop rate if available." seems to have no effect when disabling it.

![atlasloot-tooltip-bug](https://user-images.githubusercontent.com/4634611/119179166-e53bc300-ba6e-11eb-956a-aeb95f92b55b.png)

I am attaching a .txt file of all the addons I have.

[wow-addons.txt](https://github.com/Hoizame/AtlasLootClassic/files/6524321/wow-addons.txt)

**Comment by Hoizame** [comment]
Hey looks like a problerm with custom tooltips, I added a something that hopefully fix that problem

**Comment by almx** [comment]
Thank you, confirmed working well now. It does seem to add a bit too much extra space for my liking though, now there is both a line break before and after the text. Not sure this is fixable, up to you.

**Comment by Hoizame** [comment]
The line break before the source info is from me but that one after not. 
I added an option for you (next update) to disable the one from AtlasLoot
![image](https://user-images.githubusercontent.com/45636893/120072276-4da02b00-c093-11eb-8f90-f119fc7bc22e.png)
