### ISSUE TITLE
Addon affecting mouse clicking on middle of screen

### ISSUE THREAD

**Issue by Gamerslove** [Hoizame/AtlasLootClassic#123]
I didn't get a error message but I've been getting issues where I lose the ability to click in the middle of my screen when I want to rotate my camera angle or to simply click on target. The screen is showing the regular game screen, no addons up but I'm only able to click on the sides or my action bar. I have reloaded my ui several times and the problem goes away for a little while and then it shortly comes back. I started disabling addons and reloading them one at a time to see if one was the problem. It was the AtlasLootClassic 2.5.1 version. I googled to see if anyone else came across this issue and I saw a post on WoW forums from some months ago with this issue, but the last version of it. So for now, I have the addon disabled. I had a rough time last night during my raid and pvping, not knowing what the deal was lol. Anyway, thanks for keeping the addon up to date. I live on this thing!

https://us.forums.blizzard.com/en/wow/t/mouse-clicking-not-registering-in-patch-901/676126

**Comment by Hoizame** [comment]
Hi can you please type "/ ftsack" in chat next time you encounter that issue and then hover over the region where that happens.

Then CTRL+Click on the highlightet green area that prevents you from clicking and upload a screenshot?
Maybe its just a outdated lib that atlasloot loads and I upload a update later that should at least fix any outdated libary problems.

**Comment by Gamerslove** [comment]
Heyyy. Thanks for the quick response. I installed the new update that you uploaded and it's working perfectly now. Thanks!
