### ISSUE TITLE
Cooking section is missing new Azeroth recipes introduced in TBC

### ISSUE THREAD

**Issue by silverhawke249** [Hoizame/AtlasLootClassic#125]
**Module:** Crafting
**Category:** Cooking
**Items:**
- Juicy Bear Burger
- Charred Bear Kabobs
- Crunchy Spider SPurprise
- Bat Bites
- Roasted Moongraze Tenderloin
- Lynx Steak
- Captain Rumsey's Lager

**Comment by Blackwidow-sudo** [comment]
I will implement them but im not sure where to put them.
@Hoizame Since they are lower level recipes, i would make a new categorie under bcc cooking.
Like "Azeroth Recipes" or something like that. Im open for suggestions, pls let me know.
