### ISSUE TITLE
Level ranges of Classic dungeons for TBC

### ISSUE THREAD

**Issue by aribrown913** [Hoizame/AtlasLootClassic#126]
With the prepatch of TBC, they have squished most of the dungeons for Classic. For example the last boss of Uldaman, Archaedas, is level 47 in Classic but he's only level 40 in TBC. 

Here is a list of the new level ranges for the dungeons
https://wowpedia.fandom.com/wiki/Instances_by_level?oldid=1184416

**Comment by Hoizame** [comment]
Updated for the next version, thanks :)

**Comment by aribrown913** [comment]
Awesome, I know pieces of gear in dungeons were also updated for TBC. Like the chest piece from WC got upgraded from a green to blue

https://classic.wowhead.com/item=6473/armor-of-the-fang
vs
https://tbc.wowhead.com/item=6473/armor-of-the-fang
