### ISSUE TITLE
Zereketh the Unboun

### ISSUE THREAD

**Issue by anon1231823** [Hoizame/AtlasLootClassic#127]
Name should be Zereketh the Unbound

The Opera Even should be The Opera Event

Also, the chinese translation needs to be reviewed, lots of them have not been approved

**Comment by Hoizame** [comment]
Thanks is fixed.
The problem is i not speak any chinese :) If someone could review them I would push a update with them out

**Comment by anon1231823** [comment]
@Hoizame  You are missing The Opera Event

**Comment by anon1231823** [comment]
@Hoizame also there is a typo New version aviable!
