### ISSUE TITLE
AtlasLoot but only for TBC / but Pre-patch?

### ISSUE THREAD

**Issue by Mojomona** [Hoizame/AtlasLootClassic#128]
I just want to know why we can only see the loot of TBC... we are not even at the other side of the Dark Portal right? so i should see the loot of Classic only too for the moment, no? Not only TBC... I mean my character is lvl 35 BE, and i am looking for my loot. You know what i mean?

**Comment by Suggesti0ns** [comment]
It wasn't obvious to me, but clicking the "World of Warcraft" icon between "Select Module" and "Select Subcategory" at the top switches between Classic Era and BCC content

**Comment by ThaDanus** [comment]
Damn, thanks, I was looking for this as well, no explanation on the curse page.

**Comment by Hoizame** [comment]
Im working on a better visual solution for that problem.

But yes clicking on the wow symbol between the dropdowns switch between classic and bcc
