### ISSUE TITLE
BRD loot tables are fucked

### ISSUE THREAD

**Issue by Nylonhourglass** [Hoizame/AtlasLootClassic#13]
loot tables in brd changed with AQ i think but its not updated in atlasloot. 

specifically blackveil cape doesnt drop from high interrogator gerstahn it drops form houndmaster grebmar and golem skull helm is dropping from phalanx not magmus

**Comment by VexacionRT** [comment]
wowhead lists both bosses as being able to drop off both capes.  However I have only seen Spritecaster cape drop off Interrogator and Blackveil off of Houndmaster.  I think that's how it is so atlasloot has them reversed.

**Comment by Nylonhourglass** [comment]
Force of will and HoJ are also swapped

**Comment by Hoizame** [comment]
Hi I know the loottables are not perfect. The data is mostly from an old version of AtlasLoot.
The next releases covers some updates but I use the data of wowhead as its data from players that run the wowhead addon.

"Force of Will" as example https://classic.wowhead.com/item=11810
