### ISSUE TITLE
Errors TBCc

### ISSUE THREAD

**Issue by Equalsthr33** [Hoizame/AtlasLootClassic#132]
Message: ...terface\AddOns\AtlasLootClassic\Data\ClassFilter.lua:125: table index is nil
Time: Sat May 29 02:40:49 2021
Count: 1
Stack: ...terface\AddOns\AtlasLootClassic\Data\ClassFilter.lua:125: table index is nil
[string "@Interface\AddOns\AtlasLootClassic\Data\ClassFilter.lua"]:125: in main chunk

Locals: ALName = "AtlasLootClassic"
ALPrivate = <table> {
 BOX_BORDER_BACKDROP = <table> {
 }
 ADDON_MSG_PREFIX = "ATLASLOOT_MSG"
 PLAYER_NAME = "Shahahadow"
 IS_CLASSIC = false
 IMAGE_PATH = "Interface\AddOns\AtlasLootClassic\Images\"
 IS_BC = true
 BOX_BACKDROP = <table> {
 }
 COIN_TEXTURE = <table> {
 }
 CLASS_BIT_TO_CLASS = <table> {
 }
 CLASS_ICON_PATH = <table> {
 }
 CLASS_NAME_TO_ID = <table> {
 }
 CLASS_BITS = <table> {
 }
 CLASS_SORT = <table> {
 }
 ACCOUNT_LOCALE = "enUS"
 LOC_CLASSES = <table> {
 }
 ICONS_PATH = "Interface\AddOns\AtlasLootClassic\Images\Icons\"
}
AtlasLoot = <table> {
 __addonversion = "v2.2.0-bcc"
 TargetScan = <table> {
 }
 DevPrint = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:58
 Locales = <table> {
 }
 ClickHandler = <table> {
 }
 Print = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:54
 IngameLocales = <table> {
 }
 Locale = <table> {
 }
 SendAddonVersion = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:160
 BC_VERSION_NUM = 2
 Loader = <table> {
 }
 __addonrevision = 2020000
 GetColoredClassNames = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:111
 ItemString = <table> {
 }
 ItemQuery = <table> {
 }
 GetLocales = <function> defined @Interface\AddOns\AtlasLootClassic\Locales\Locales.lua:12
 SlashCommands = <table> {
 }
 LibBabble = <table> {
 }
 Init = <table> {
 }
 TooltipScan = <table> {
 }
 OnProfileChanged = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:64
 AtlasLootDBDefaults = <table> {
 }
 Tooltip = <table> {
 }
 MiniMapButton = <table> {
 }
 IsAddonUpdateAviable = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:169
 CLASSIC_VERSION_NUM = 1
 AddInitFunc = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:95
 OnInitialize = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:74
 GetGameVersion = <function> defined @Interface\AddOns\AtlasLootClassic\Init.lua:58
 ItemInfo = <table> {
 }
 Data = <table> {
 }
}
ClassFilter = <table> {
}
AL = <table> {
}
Requirements = <table> {
 HasPvPRequirements = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5532
 GetPvPRankInfo = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5509
 BuildClassString = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5485
 GetPvPRankIcon = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5519
 HasRequirements = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5528
 GetReqString = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5536
 GetPvPRankIconForItem = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5523
 ClassCanUseItem = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5501
 GetPvPRankName = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5514
}
GetItemInfoInstant = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
format = <function> defined =[C]:-1
bit_band = <function> defined =[C]:-1
CLASS_BITS = <table> {
 HUNTER = 4
 WARRIOR = 1
 PALADIN = 2
 MAGE = 128
 PRIEST = 16
 WARLOCK = 256
 DRUID = 1024
 SHAMAN = 64
 ROGUE = 8
}
CLASS_SORT = <table> {
 1 = "WARRIOR"
 2 = "PALADIN"
 3 = "HUNTER"
 4 = "ROGUE"
 5 = "PRIEST"
 6 = "SHAMAN"
 7 = "MAGE"
 8 = "WARLOCK"
 9 = "DRUID"
}
CLASS_NAME_TO_ID = <table> {
 HUNTER = 3
 WARRIOR = 1
 ROGUE = 4
 MAGE = 7
 PRIEST = 5
 WARLOCK = 8
 DRUID = 9
 PALADIN = 2
 SHAMAN = 6
}
C = <table> {
 HUNTER = 4
 WARRIOR = 1
 PALADIN = 2
 MAGE = 128
 PRIEST = 16
 WARLOCK = 256
 D

------------------------------------ ERROR 2/22 ------------------------------------

Message: Interface\AddOns\Quartz\modules\Player.lua:230: attempt to call global 'GetActiveSpecGroup' (a nil value)
Time: Sat May 29 02:41:36 2021
Count: 1
Stack: Interface\AddOns\Quartz\modules\Player.lua:230: attempt to call global 'GetActiveSpecGroup' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Quartz\modules\Player.lua"]:230: in function <Interface\AddOns\Quartz\modules\Player.lua:229>
[string "@Interface\AddOns\Quartz\modules\Player.lua"]:237: in function `UpdateChannelingTicks'
[string "@Interface\AddOns\Quartz\modules\Player.lua"]:105: in function <Interface\AddOns\Quartz\modules\Player.lua:97>
[string "=[C]"]: ?
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

------------------------------------ Error 3/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:08:32 2021
Count: 1
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:110: in function `UpdateFilter'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:210: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:179: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:765: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:735: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:714: in function `ButtonOnClick'
...
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:879: in function `Toggle'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:20: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:58: in function `Run'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:49: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4825: in function <Interface\FrameXML\ChatFrame.lua:4771>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4488: in function <Interface\FrameXML\ChatFrame.lua:4487>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4524: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 

------------------------------------ error 4/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:08:32 2021
Count: 1
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:110: in function `UpdateFilter'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:210: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:179: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:249: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:224>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:879: in function `Toggle'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:20: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:58: in function `Run'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:49: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4825: in function <Interface\FrameXML\ChatFrame.lua:4771>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4488: in function <Interface\FrameXML\ChatFrame.lua:4487>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4524: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 

------------------------------------ ERROR 5/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:11:53 2021
Count: 51
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\Button\Item_type.lua"]:458: in function <...terface\AddOns\AtlasLootClassic\Button\Item_type.lua:445>

Locals: 

------------------------------------ Error 6/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:09:58 2021
Count: 2
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:110: in function `UpdateFilter'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:210: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:179: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:765: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:735: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:714: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:80: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:610: in function `onLoadFunction'
[string "@Interface\AddOns\AtlasLootClassic\Loader.lua"]:163: in function `LoadModule'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:668: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:230: in function <...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:228>

Locals: 

------------------------------------ Error 7/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:17:42 2021
Count: 6
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:110: in function `UpdateFilter'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:210: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:179: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:765: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:735: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:714: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:80: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:610: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:558>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:795: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:782>

Locals: 

------------------------------------ Error 8/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:10:01 2021
Count: 2
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:110: in function `UpdateFilter'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:210: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:179: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:765: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:735: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:714: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:230: in function <...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:228>

Locals: 

------------------------------------ Error 9/11 ------------------------------------

Message: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
Time: Sat May 29 05:11:53 2021
Count: 2
Stack: Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua:83: attempt to call field 'ClassCanUseItem' (a nil value)
[string "=[C]"]: in function `ClassCanUseItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:83: in function `UpdateFilterItem'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:110: in function `UpdateFilter'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:210: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:179: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:765: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:757: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:208: in function <...face\AddOns\AtlasLootClassic\GUI\Template_Select.lua:206>

Locals:

**Comment by Hoizame** [comment]
see #129
Update should be out in a few minutes
