### ISSUE TITLE
v2.2.1 Lua Error - table index is nil

### ISSUE THREAD

**Issue by boktai1000** [Hoizame/AtlasLootClassic#135]
**Lua error**

Message: ...terface\AddOns\AtlasLootClassic\Data\ClassFilter.lua:125: table index is nil
Time: Sat May 29 22:14:30 2021
Count: 1
Stack: ...terface\AddOns\AtlasLootClassic\Data\ClassFilter.lua:125: table index is nil
[string "@Interface\AddOns\AtlasLootClassic\Data\ClassFilter.lua"]:125: in main chunk

Locals: ALName = "AtlasLootClassic"
ALPrivate = <table> {
 BOX_BORDER_BACKDROP = <table> {
 }
 ADDON_MSG_PREFIX = "ATLASLOOT_MSG"
 PLAYER_NAME = "Domsix"
 IS_CLASSIC = false
 IMAGE_PATH = "Interface\AddOns\AtlasLootClassic\Images\"
 IS_BC = true
 BOX_BACKDROP = <table> {
 }
 COIN_TEXTURE = <table> {
 }
 CLASS_BIT_TO_CLASS = <table> {
 }
 CLASS_ICON_PATH = <table> {
 }
 CLASS_NAME_TO_ID = <table> {
 }
 CLASS_BITS = <table> {
 }
 CLASS_SORT = <table> {
 }
 ACCOUNT_LOCALE = "enUS"
 LOC_CLASSES = <table> {
 }
 ICONS_PATH = "Interface\AddOns\AtlasLootClassic\Images\Icons\"
}
AtlasLoot = <table> {
 __addonversion = "v2.2.0-bcc"
 TargetScan = <table> {
 }
 DevPrint = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:58
 Locales = <table> {
 }
 ClickHandler = <table> {
 }
 Print = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:54
 IngameLocales = <table> {
 }
 Locale = <table> {
 }
 SendAddonVersion = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:160
 BC_VERSION_NUM = 2
 Loader = <table> {
 }
 __addonrevision = 2020000
 GetColoredClassNames = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:111
 ItemString = <table> {
 }
 ItemQuery = <table> {
 }
 GetLocales = <function> defined @Interface\AddOns\AtlasLootClassic\Locales\Locales.lua:12
 SlashCommands = <table> {
 }
 LibBabble = <table> {
 }
 Init = <table> {
 }
 TooltipScan = <table> {
 }
 OnProfileChanged = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:64
 AtlasLootDBDefaults = <table> {
 }
 Tooltip = <table> {
 }
 MiniMapButton = <table> {
 }
 IsAddonUpdateAviable = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:169
 CLASSIC_VERSION_NUM = 1
 AddInitFunc = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:95
 OnInitialize = <function> defined @Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:74
 GetGameVersion = <function> defined @Interface\AddOns\AtlasLootClassic\Init.lua:58
 ItemInfo = <table> {
 }
 Data = <table> {
 }
}
ClassFilter = <table> {
}
AL = <table> {
}
Requirements = <table> {
 HasPvPRequirements = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5532
 GetPvPRankInfo = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5509
 BuildClassString = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5485
 GetPvPRankIcon = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5519
 HasRequirements = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5528
 GetReqString = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5536
 GetPvPRankIconForItem = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5523
 ClassCanUseItem = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5501
 GetPvPRankName = <function> defined @Interface\AddOns\AtlasLootClassic\Data\Requirements.lua:5514
}
GetItemInfoInstant = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
format = <function> defined =[C]:-1
bit_band = <function> defined =[C]:-1
CLASS_BITS = <table> {
 HUNTER = 4
 WARRIOR = 1
 PALADIN = 2
 MAGE = 128
 PRIEST = 16
 WARLOCK = 256
 DRUID = 1024
 SHAMAN = 64
 ROGUE = 8
}
CLASS_SORT = <table> {
 1 = "WARRIOR"
 2 = "PALADIN"
 3 = "HUNTER"
 4 = "ROGUE"
 5 = "PRIEST"
 6 = "SHAMAN"
 7 = "MAGE"
 8 = "WARLOCK"
 9 = "DRUID"
}
CLASS_NAME_TO_ID = <table> {
 HUNTER = 3
 WARRIOR = 1
 ROGUE = 4
 MAGE = 7
 PRIEST = 5
 WARLOCK = 8
 DRUID = 9
 PALADIN = 2
 SHAMAN = 6
}
C = <table> {
 HUNTER = 4
 WARRIOR = 1
 PALADIN = 2
 MAGE = 128
 PRIEST = 16
 WARLOCK = 256
 DRUID

**Comment by Hoizame** [comment]
This error is from v2.2.0-bcc and is fixed with 2.2.1
