### ISSUE TITLE
Maps Missing

### ISSUE THREAD

**Issue by ramboozer** [Hoizame/AtlasLootClassic#138]
I noticed the data-tbc.lua was updated to including the newer dungeons / raids to have the maps within Atlas, I did this previously myself and it was working flawlessly. when I updated today I noticed you changed as I changed but it no longer is showing the maps at all.

Updated Today 6/6/2021
![image](https://puu.sh/HMEGk/70f0be6826.png)

Old Version - I Hotfixed
![image](https://cdn.discordapp.com/attachments/770674447496773662/850055412815626240/Untitled.png)

This was done very fast and a few things were not typed correctly however they still worked (Talking about the map arrays) on my end

[hotfix.zip](https://github.com/Hoizame/AtlasLootClassic/files/6603716/hotfix.zip)

**Comment by Hoizame** [comment]
Are you using the Atlas modules from curseforge?
https://www.curseforge.com/wow/addons/atlas-classicwow
https://www.curseforge.com/wow/addons/atlas-burningcrusade

**Comment by jrbarto** [comment]
> Are you using the Atlas modules from curseforge?
> https://www.curseforge.com/wow/addons/atlas-classicwow
> https://www.curseforge.com/wow/addons/atlas-burningcrusade

Can confirm this fixed it for me at least. I was using the AtlasLootClassic_Maps previously, without having atlas-classicwow or atlas-burningcrusade installed at all. After installing those two the maps are all working, and I don't even need AtlasLootClassic_Maps anymore.

**Comment by Neutrinobeam** [comment]
The .atlasModules are hard coded to point at the Atlas modules. So AtlasMaps_GetMapPath in GUI.lua always looks for the Atlas module maps regardless of their actual presence.

Making a fork for this one suggestion seems like a bit much, but line 74 of GUI.lua could be a branch instead:

```lua
if IsMapsModuleAviable(nil) then
    GUI.frame.contentFrame.map.atlasMapModule = nil
else
    GUI.frame.contentFrame.map.atlasMapModule = moduleData[dataID].items[bossID].AtlasModule or moduleData[dataID].AtlasModule
end
```
