### ISSUE TITLE
LUA Error with Collections

### ISSUE THREAD

**Issue by Tga123** [Hoizame/AtlasLootClassic#14]
### Getting LUA Error when select "Collections" in first drop down menu.
Date: 2019-09-13 13:18:30
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\AtlasLootClassic\Button\Set_type.lua line 50:
   bad argument `#2` to "format" (string expected, got nil)
Debug:
   [C]: ?
   [C]: ?
   ...nterface\AddOns\AtlasLootClassic\Button\Set_type.lua:50: OnSet()
   AtlasLootClassic\Button\Button.lua:653: SetType()
   AtlasLootClassic\Button\Button.lua:625: SetContentTable()
   AtlasLootClassic\GUI\ItemFrame.lua:190: Refresh()
   AtlasLootClassic\GUI\GUI.lua:156:
      AtlasLootClassic\GUI\GUI.lua:29
   AtlasLootClassic\GUI\GUI.lua:735: ButtonOnClick()
   ...face\AddOns\AtlasLootClassic\GUI\Template_Select.lua:84: SetSelected()
   ...face\AddOns\AtlasLootClassic\GUI\Template_Select.lua:125: SetData()
   AtlasLootClassic\GUI\GUI.lua:705: ButtonOnClick()
   ...face\AddOns\AtlasLootClassic\GUI\Template_Select.lua:84: SetSelected()
   ...face\AddOns\AtlasLootClassic\GUI\Template_Select.lua:125: SetData()
   AtlasLootClassic\GUI\GUI.lua:684: ButtonOnClick()
   ...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:159: SetSelected()
   ...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:80: SetData()
   AtlasLootClassic\GUI\GUI.lua:580: ?()
   AtlasLootClassic\Loader.lua:87:
      AtlasLootClassic\Loader.lua:75
   [C]: LoadAddOn()
   AtlasLootClassic\Loader.lua:197: LoadModule()
   AtlasLootClassic\GUI\GUI.lua:638: ButtonOnClick()
   ...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:159: SetSelected()
   ...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:230:
      ...ce\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua:228
Locals:
 `<none>`

**Comment by Hoizame** [comment]
Looks like something change the global table `RAID_CLASS_COLORS` I add a check/fix for that into the next version. What addons are you using?
