### ISSUE TITLE
Tons of LUA errors

### ISSUE THREAD

**Issue by deusduce2** [Hoizame/AtlasLootClassic#145]
**Lua error**
Message: ...terface\AddOns\AtlasLootClassic\Button\Item_type.lua:119: attempt to index upvalue 'VendorPrice' (a nil value)
Time: Tue Jun 15 01:08:22 2021
Count: 2
Stack: ...terface\AddOns\AtlasLootClassic\Button\Item_type.lua:119: attempt to index upvalue 'VendorPrice' (a nil value)
[string "@Interface\AddOns\AtlasLootClassic\Button\Item_type.lua"]:119: in function `OnSet'
[string "@Interface\AddOns\AtlasLootClassic\Button\Button.lua"]:684: in function `SetType'
[string "@Interface\AddOns\AtlasLootClassic\Button\Button.lua"]:651: in function `SetContentTable'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:183: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:183: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:35>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:781: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:751: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:84: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:125: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:730: in function `ButtonOnClick'
...
[string "@Interface\AddOns\AtlasLootClassic\Loader.lua"]:166: in function `LoadModule'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:684: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:230: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:228>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:895: in function `Toggle'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:20: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:58: in function `Run'
[string "@Interface\AddOns\AtlasLootClassic\MiniMapButton.lua"]:51: in function <Interface\AddOns\AtlasLootClassic\MiniMapButton.lua:40>
[string "@Interface\AddOns\TitanClassic\LDBToTitanClassic.lua"]:273: in function <Interface\AddOns\TitanClassic\LDBToTitanClassic.lua:271>

Locals: button = AtlasLoot_Button_1 {
 0 = <userdata>
 SetContentTable = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:542
 RawName = "Subterranean Cape"
 GetTypeFunctions = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:731
 ItemID = 14149
 formatTab = <table> {
 }
 phaseIndicator = AtlasLoot_Button_1_phaseIndicator {
 }
 SetPreSet = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:532
 highlightBg = AtlasLoot_Button_1_highlightBg {
 }
 secButton = AtlasLoot_Button_1_secButton {
 }
 favourite = AtlasLoot_Button_1_favourite {
 }
 SetType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:675
 factionIcon = AtlasLoot_Button_1_factionIcon {
 }
 Clear = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:479
 Droprate = 34.820000
 SetDifficultyID = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:723
 extra = AtlasLoot_Button_1_extra {
 }
 __atlaslootinfo = <table> {
 }
 GetSecTypeFunctions = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:735
 AddEnhancedDescription = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:859
 completed = AtlasLoot_Button_1_completed {
 }
 SetNpcID = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:727
 count = AtlasLoot_Button_1_count {
 }
 overlay = AtlasLoot_Button_1_overlay {
 }
 SetExtraType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:704
 SetSecType = <function> define
 
**Describe the bug**
Any time AL is used (opened, click a button, change directories, etc) a LUA error pops up and something (differs each time) goes wrong or doesn't go at all.

**To Reproduce**
Install AL and attempt to use.

**Expected behavior**
Shouldn't be receiving LUA errors, should be working without issue.

**Screenshots**
![WoWScrnShot_061521_011214](https://user-images.githubusercontent.com/83378039/122017425-cdf2ab80-cd76-11eb-8681-0c46f1a45af1.jpg)

**Comment by Blackwidow-sudo** [comment]
@deusduce2 Do you still have these Errors?
Have you tried to re-install it or delete cache directory?

**Comment by deusduce2** [comment]
> @deusduce2 Do you still have these Errors?
> Have you tried to re-install it or delete cache directory?

I will check tonight, I haven't been playing in a little bit and I turned off AL due to the issues. I don't recall if I uninstalled it or not, but if I did I will reinstall or update to whatever new version is available and check, then get back to you.

Thanks for the attention to this!
