### ISSUE TITLE
Missing Badge of Justice helmets

### ISSUE THREAD

**Issue by tilliwilli** [Hoizame/AtlasLootClassic#147]
**Module:** TBC Classic
**Category:** Collections
**Loottable:** 'Badge of Justice' Vendor
**Items:** e.g. the Faceguard of Determination (https://tbc.wowhead.com/item=32083/faceguard-of-determination)

**Additional context**: 
I actually totally forgot that there are also (already) non-resistance helmets for each armor class available for Badges of Justice. They are not listed in AtlasLoot, I only see all these fire resistance items for Cloth/Leather/Mail/Plate.
Since I never really checked the full item list G'eras has available, I only stumbled upon that when I saw someone wearing that helmet ingame...

**Comment by Blackwidow-sudo** [comment]
Issue solved.
