### ISSUE TITLE
Flamewrought Key

### ISSUE THREAD

**Issue by Ranadicus** [Hoizame/AtlasLootClassic#152]
**Module: TBC CLassic**
**Category: Factions**
**Loottable: Honor Hold/Thrallmar**
**Items: Flamewrought Key**

**The Flamewrought Key is on the honored tab instead of revered**

**Comment by Blackwidow-sudo** [comment]
the more i look in to it, the more items i find in the wrong list.
I wrote a fix but im not done yet. There are some recipes that i have to move to the tbc section.
I will make a pull request soon, but it seems like this repo is not active.

**Comment by Hoizame** [comment]
Hey when you make a pull request i take alook into it and will merge it :)

I just not have the time myself to update my addons or even play wow at the moment

**Comment by Blackwidow-sudo** [comment]
> Hey when you make a pull request i take alook into it and will merge it :)
> I just not have the time myself to update my addons or even play wow at the moment

Good to see :)
But i have to admit: I dont have any experience in WoW-Addon Development nor Lua (im coming from JS).
Moving items to other lists was easy but i did not dig deep enough to make a Release-Build.
I dont know if i have enough time to get familiar with the whole project.

**Comment by Hoizame** [comment]
moving items into the list is enough 
I will update the rest

**Comment by Blackwidow-sudo** [comment]
This issue is solved.
