### ISSUE TITLE
Add 'Fishing Profession' Items next to Cooking & First Aid

### ISSUE THREAD

**Issue by fraisie** [Hoizame/AtlasLootClassic#155]
There are a lot more Fishing items in the game now thanks to the Old Man Barlo dailies,
it would be nice to be able to see all the Fishing related items you can acquire in the game.

Currently Fishing is left out of the secondary professions list for some reason.

**Comment by Blackwidow-sudo** [comment]
I just looked into the [wowhead fishing guide](https://tbc.wowhead.com/guides/fishing-profession-burning-crusade-classic) and i will add at least the rareloot from the fishing daily.
If you want i would also add the Buff-Items?
