### ISSUE TITLE
BoP Blacksmithing crafted items listed as 385 skill instead of 375

### ISSUE THREAD

**Issue by boktai1000** [Hoizame/AtlasLootClassic#164]
**Describe the bug**
There are a number of Blacksmithing items that are listed as 385 Blacksmithing both in their tooltip, as well as in the Crafting -> Blacksmithing module. In all cases these are the 2nd and 3rd level BoP Blacksmithing profession crafts that have this issue.

List of items affected (that I'm aware of):

Dragonmaw
Dragonstrike
Deep Thunder
Stormherald
Blazefury
Blazeguard
Lionheart Executioner
Lionheart Champion
Wicked Edge of the Planes
Black Planar Edge
Bloodmoon
Mooncleaver
Embrace of the Twisting Nether
Twisting Nether Chain Shirt
Ancient Bulwark of the Kings
Bulwark of Kings

**To Reproduce**
View the tooltip of an item in a chat link, character menu, or bag item. The tooltip does not show when mouse-over the items from AtlasLoot itself

**Expected behavior**
Each item should say **Blacksmithing (375)** instead of **Blacksmithing (385)**

**Screenshots**

**Weapons - Maces**

**Dragonmaw** - https://tbc.wowhead.com/item=28438/dragonmaw
![image](https://user-images.githubusercontent.com/9054563/129410953-93542223-7c40-40b1-adcc-d92b23678062.png)

**Dragonstrike** - https://tbc.wowhead.com/item=28439/dragonstrike
![image](https://user-images.githubusercontent.com/9054563/129410996-9dad2bd9-9a05-4929-9cdd-fc0dda14181d.png)

**Stormherald** - https://tbc.wowhead.com/item=28442/stormherald
![image](https://user-images.githubusercontent.com/9054563/129411088-0571bea1-de2a-4c1d-aefd-6b27d926111e.png)

**Deep Thunder** - https://tbc.wowhead.com/item=28441/deep-thunder
![image](https://user-images.githubusercontent.com/9054563/129411113-873ed479-7e5e-4eb2-95de-5b3c0784d480.png)

**Weapons - Swords**

**Blazefury** - https://tbc.wowhead.com/item=28427/blazefury
![image](https://user-images.githubusercontent.com/9054563/129411192-64fb4cf3-895c-4c1b-b595-0e26c52c3334.png)

**Blazeguard** - https://tbc.wowhead.com/item=28426/blazeguard
![image](https://user-images.githubusercontent.com/9054563/129411219-df1aeea0-cd11-42c2-9f30-3f8f0c4c64d5.png)

**Lionheart Executioner** - https://tbc.wowhead.com/item=28430/lionheart-executioner
![image](https://user-images.githubusercontent.com/9054563/129411258-53af6757-ff60-45e4-88c5-dc2afab692bd.png)

**Lionheart Champion** - https://tbc.wowhead.com/item=28429/lionheart-champion
![image](https://user-images.githubusercontent.com/9054563/129411280-b53d7bfa-58a3-415d-b390-3f1de1fd3fe3.png)

**Weapons - Axes**

**Wicked Edge of the Planes** - https://tbc.wowhead.com/item=28433/wicked-edge-of-the-planes
![image](https://user-images.githubusercontent.com/9054563/129411347-eb3e32cc-7e5e-4f7d-82a4-ad8395edbcb5.png)

**Black Planar Edge** - https://tbc.wowhead.com/item=28432/black-planar-edge
![image](https://user-images.githubusercontent.com/9054563/129411372-46fb8d86-a130-4a11-bb4f-64bb63953e2c.png)

**Bloodmoon** - https://tbc.wowhead.com/item=28436/bloodmoon
![image](https://user-images.githubusercontent.com/9054563/129411417-3ffdd929-d248-44cb-898c-d832b7a33801.png)

**Mooncleaver** - https://tbc.wowhead.com/item=28435/mooncleaver
![image](https://user-images.githubusercontent.com/9054563/129411431-6baaa83f-9f38-4bd3-bedf-0c484cca7135.png)

**Armor - Chest**

**Mail**

**Embrace of the Twisting Nether** - https://tbc.wowhead.com/item=23565/embrace-of-the-twisting-nether
![image](https://user-images.githubusercontent.com/9054563/129412250-e7a3c8a5-d1ad-4cc0-8289-1ed2b760e49f.png)

**Twisting Nether Chain Shirt** - https://tbc.wowhead.com/item=23564/twisting-nether-chain-shirt
![image](https://user-images.githubusercontent.com/9054563/129412291-eec95ae2-42f4-44d3-8b38-2b8d38f929c7.png)

**Plate**

**Bulwark of the Ancient Kings** - https://tbc.wowhead.com/item=28485/bulwark-of-the-ancient-kings
![image](https://user-images.githubusercontent.com/9054563/129411813-52f8dd93-6e8c-48ee-8835-80d014882dd5.png)

**Bulwark of Kings** - https://tbc.wowhead.com/item=28484/bulwark-of-kings
![image](https://user-images.githubusercontent.com/9054563/129411782-40804b5d-fc9d-4cac-94de-ba94ab51a3e4.png)

**Additional context**
When reviewing Wowhead as well for the "difficulty" of the crafting for each of them for orange / yellow / green / grey skill ups, they all appeared to have the same listed as well. Screenshot below showcasing that from Wowhead.

![image](https://user-images.githubusercontent.com/9054563/129412512-c403acc7-042b-48e2-bb04-7db6fbef5ed5.png)

**Comment by Blackwidow-sudo** [comment]
As far as i know:
The displayed number is not the skill zu need to build it, but its how long the recipe gives skill points.

**Comment by boktai1000** [comment]
That also seems a bit inconsistent with some other items such as Sulfuron Hammer though (I've begun to dig a bit deeper with some comparisons / references)

![image](https://user-images.githubusercontent.com/9054563/129457040-416c7668-a240-419f-9eeb-0324f4210469.png)

https://tbc.wowhead.com/spell=21161/sulfuron-hammer

![image](https://user-images.githubusercontent.com/9054563/129457044-7cfd4524-88cb-478c-9c49-d9e3974ef292.png)

**Comment by boktai1000** [comment]
And digging deeper into the rabbit hole I see references to 390 / 397 / 405 with Alchemy which is very confusing as well

![image](https://user-images.githubusercontent.com/9054563/129457169-1c7e97bb-da4e-4f27-b7f7-061c3bc06994.png)


As well as 385 / 392 / 400 here for example

![image](https://user-images.githubusercontent.com/9054563/129457163-b061f294-cf3b-4569-af5a-ba583130e63b.png)

**Comment by Blackwidow-sudo** [comment]
Well we have to wait until @Hoizame says something about this.
I always assumed the displayed number is how long the recipe remains red.
But seems like it is inconsistent then, according to your picture from the Sulfuron Hammer.

**Comment by Hoizame** [comment]
At the time I created that database I used much old data and it looks like some were wrong also 

I updated most of the profession ranks now
