### ISSUE TITLE
Don't show "cloak" when filter is active

### ISSUE THREAD

**Issue by CryptoLogiq** [Hoizame/AtlasLootClassic#166]
-- Problem ?
The cloak pieces are not visible for all class's...

-- Reproduce ?
Simply activate a filter for all classes that can equip with something other than cloth, but a cape is always made of Cloth...

-- Example
Activate a Paladin Filter and you don't show any cloak...

-- The filter is not good, because you have to deactivate it to find all this because cloak is not in filter mode. 

--> The Filter's do ignore cloak pieces =)

**Comment by Blackwidow-sudo** [comment]
I am looking into it right now.
I couldnt come up with a simple solution right now.
The Problem:
If i allow Cloth for all classes and then exclude the items via the stats => Druidfilter will show all Cloth-Pieces.
I have to make some kind of exception for Cloak+Cloth...

**Comment by Hoizame** [comment]
I have the fix done already just not committed.
I'll upload that later when i'm at home and release the new version.
