### ISSUE TITLE
Whole add-on missing

### ISSUE THREAD

**Issue by MagnumPiCactus** [Hoizame/AtlasLootClassic#167]
I'm not sure what's going on but AtlasLootClassic isn't showing up. Earlier yesterday it was working perfectly fine and then later that day it was greyed out in curseforge. This morning it wasn't with my other addons at all. I've tried manually installing it multiple times but it won't show up in the addons menu or anywhere in the game even when the atlaslootclassic folder is in the add-on folder. I've asked around and no one else seems to be having any problems with it.

**Comment by Blackwidow-sudo** [comment]
I dont think this is a problem with AtlasLootClassic.
There is something wrong with CurseForge i believe.
I use WoWUp as Addon-Manager and had trouble getting the AtlasLootClassic-Update. A manual install solved it.
But now i have the same problem with other Addons (Auctionator, DBM...). WoWUp got also an update today but it didnt really fix that issue.
WoWUp says there is something wrong with the source (CurseForge).

**Comment by Hoizame** [comment]
Jep there is some problem with curseforge 
I reuploaded the addon and the version is still not detected.

**Comment by MagnumPiCactus** [comment]
It wasn't fixed but that's not the addons problem. It showed back up on curseforge app. I guess case closed?
