### ISSUE TITLE
Background color is reflected across the X-axis

### ISSUE THREAD

**Issue by Equalsthr33** [Hoizame/AtlasLootClassic#169]
**Lua error**
No error

**Describe the bug**
When using the Background color/alpha color picker, the colors are opposite of its exact location on the circle reflected across the X-axis.

**To Reproduce**
Use the color picker (Windows > Atlasloot > "Background color/alpha")

**Expected behavior**
Choose the color according to the location on the color circle.

**Screenshots**
https://gyazo.com/128066d5e702c394a19d6a77ef05246e

**Additional context**

**Comment by Blackwidow-sudo** [comment]
Is fixed now 👍
