### ISSUE TITLE
An option that lets us see specific type of armor only.

### ISSUE THREAD

**Issue by Nillx** [Hoizame/AtlasLootClassic#17]
I would love an option that lets us filter the loot from bosses. Something like showing only cloth gear and hiding the rest. 

Or something even better (thats too much i think). An option to search for specific armor slot, ex: Typing in the search box "Cloth gloves" and it shows every possible dungeon or raid drop gloves.

**Comment by Hoizame** [comment]
Hey the configurable filter is planned yes
Search gets added with #4 when I have the time :)
