### ISSUE TITLE
Possible to add Brewfest to the World Events

### ISSUE THREAD

**Issue by chillface** [Hoizame/AtlasLootClassic#178]
**Is your feature request related to a problem? Please describe.**
Brewfest is coming up in a couple weeks and was looking in atlasloot for it to see the trinkets/mount/items

**Describe the solution you'd like**
Brewfest to be added into the world events

**Additional context**

**Comment by Blackwidow-sudo** [comment]
I couldnt find any sources which items will be implemeted in the tbc brewfest.
Do you have an article or something where everything is listed?

**Comment by chillface** [comment]
I do not have a source saying that we will be getting Coren Direbrew in this upcoming Brewfest but since Ahune was present during the Midsummer Festival, I was guessing that Coren would also be available with his loot table seen here. 
https://tbc.wowhead.com/npc=23872/coren-direbrew

**Comment by Blackwidow-sudo** [comment]
Ok i will add him and implement the rest of the event items when i know more about what will be added.

**Comment by Blackwidow-sudo** [comment]
Im not sure if al the data is correct on your link.
I will wait until there is an article on wowhead on bcc-brewfest, like they did before with the midsummer event.

**Comment by Blackwidow-sudo** [comment]
I found this [Article](https://bittsguides.com/brewfest-and-coren-direbrew-guide/) though i couldnt find out Coren Direbrew's level. I assume he is lvl 73 like Ahune was.

**Comment by sintaxx** [comment]
https://tbc.wowhead.com/npc=23872/coren-direbrew

this is his loot table (Coren Direbrew)

**Comment by sintaxx** [comment]
```			[NORMAL_DIFF] = {
				{ 1,  38289 }, -- Coren's Lucky Coin
				{ 2,  38288 }, -- Direbrew Hops
				{ 3,  38290 }, -- Dark Iron Smoking Pipe
				{ 4,  38287 }, -- Empty Mug of Direbrew
				{ 6,  37127 }, -- Brightbrew Charm
				{ 7,  37128 }, -- Balebrew Charm
				{ 8,  37597 }, -- Direbrew's Shanker'
				{ 9,  37863 }, -- Direbrew's Remote
				{ 10,  33977 }, -- Swift Brewfest Ram
				{ 11,  37828 }, -- Great Brewfest Kodo
			},
```

**Comment by Blackwidow-sudo** [comment]
> 
> 
> https://tbc.wowhead.com/npc=23872/coren-direbrew
> 
> this is his loot table (Coren Direbrew)

Yep its already done.
But it was unclear if [Direbrew's Shanker](https://tbc.wowhead.com/item=37597/direbrews-shanker) will be available because this item was added in a later phase of BC according to a videoguide.
#180 Has it all in there.

**Comment by swolltitan** [comment]
the shanker has been added (got it on my hunter)
