### ISSUE TITLE
Add Season 2, 3 and 4 Gladiator sets

### ISSUE THREAD

**Issue by Tenies** [Hoizame/AtlasLootClassic#179]

**Comment by Hoizame** [comment]
With build 2.5.2.40045 they are still not in the game files so we have to waite here :(

**Comment by Jorvanus** [comment]
Surely season 2 is in game now though?  Latest release doesn't have them yet. :-(

**Comment by Jorvanus** [comment]
Surely in the game now but I can't see them in latest release?
