### ISSUE TITLE
Please tie back into atlas maps

### ISSUE THREAD

**Issue by beren12** [Hoizame/AtlasLootClassic#18]
Please restore the atlas maps plugin so we can see everything in one place. map, bosses, quest items, atlas quest, etc.

**Comment by Hoizame** [comment]
Atlas integration is coming when I have the time :)
So much to do :D

**Comment by Phatcat** [comment]
Seeing as Atlas has released for classic, are you going to take down https://www.curseforge.com/wow/addons/atlaslootclassic_maps which you clearly state within the page itself that you would, if they ever did update (which they have)?

**Comment by Hoizame** [comment]
Yes AtlasLootClassic gets a info where to get the maps and the project gets deleted when the support for Atlas maps is done.
The maps part should be done next week the full intgration maybe takes some time

**Comment by beren12** [comment]
Any chance you had time to make progress on this? You've done amazing work so far I just miss having 1 button with everything: map, loot, quests and quest items.

**Comment by beren12** [comment]
Any chance you still plan on merging back inside atlas? I use both daily still but miss the tight integration it used to have.

**Comment by rbpaiett** [comment]
I also support the motions to integrate this into Atlas/Atlas Maps for Classic!

**Comment by beren12** [comment]
Is there anything someone can do to help start this? I'm not sure what has changed/removed since the classic version was adapted from the old versions that worked together.
