### ISSUE TITLE
Hallows End

### ISSUE THREAD

**Issue by chillface** [Hoizame/AtlasLootClassic#183]
**Is your feature request related to a problem? Please describe.**
Since Brewfest and Midsummer both had their items in the game, Could you add all the items for the Headless Horsemen for next months Halloween event?

His loot table is here for reference - https://tbc.wowhead.com/npc=23682/headless-horseman
**Describe the solution you'd like**
Would be nice to pull up atlas loot and link stuff before hand so people can prepare their schedules to farm for these events.
**Additional context**

**Comment by Tenies** [comment]
Headless Horseman is already under SM GY! Next release will also include him under his event (Hallow's End).
