### ISSUE TITLE
Very small mistake(?) in Headless Horseman

### ISSUE THREAD

**Issue by cloudbells** [Hoizame/AtlasLootClassic#186]
**Module:**
AtlasLootClassic/AtlasLootClassic_DungeonsAndRaids/data.lua

**Category:**
Scarlet Monastery Graveyard ([line 1168](https://github.com/Hoizame/AtlasLootClassic/blob/6edc4ed6ca6c47f5ca29f9accebe0f998688e394/AtlasLootClassic_DungeonsAndRaids/data.lua#L1168))

**Loottable:**
Headless Horseman

**Items:**
Tome of Thomas Thomson

**Additional context**
According to [wowwiki](https://wowwiki-archive.fandom.com/wiki/Tome_of_Thomas_Thomson) and [live Wowhead](https://www.wowhead.com/item=33277/tome-of-thomas-thomson) this item is provided as part of a quest _after_ Headless Horseman is dead by an NPC nearby called [Sir Thomas](https://www.wowhead.com/npc=23904/sir-thomas) and doesn't seem to drop off the body itself.

**Comment by Blackwidow-sudo** [comment]
> Sir Thomas is the Headless Horseman. At least he was the Headless Horseman before he went insane. 
> After you vanquish the Headless Horseman during the Hallows End event, the ghost of Sir Thomas will appear.

So i guess we can leave it as it is

**Comment by Tenies** [comment]
Many tbc databases have this as a drop. It may also be just a quest item as you take "Free at Last!".
Few more days and we'll learn. Hallow's End starts probably 18/10.
