### ISSUE TITLE
Ability to name new lists (and possibly rename existing ones)

### ISSUE THREAD

**Issue by Kolgrath** [Hoizame/AtlasLootClassic#187]
**Currently we are unable to give new lists a name.**

**When clicking "Add new list" we are only given the options to "Accept" or "Cancel". Clicking "Accept" simply names the list as "List", and each subsequent new list also is named "List". There is no text box for entering a name, and there is currently no way that I can find to re-name a list. A solution would be to add a text box where we could enter our desired new name for the list before clicking "Accept".**

**An example in practice would be having a list called Pre-Raid BiS, T4 BiS, T5 BiS, etc. It would be a great feature to be able to give those names to keep everything organized.**

**Comment by Blackwidow-sudo** [comment]
It is already possible to name your lists:

![namedlist](https://user-images.githubusercontent.com/60359431/136469985-f09d223f-fd32-438e-ad08-d8cfc1d70b9c.png)

First you click on [Add new list] and accept.
Then you can change the name in the Textbox under it (in the red box on my picture).
