### ISSUE TITLE
If you are not going tie into Atlas Maps please add  AtlasQuest - Fan Update into AtlasLootClassic

### ISSUE THREAD

**Issue by Hyattmeister** [Hoizame/AtlasLootClassic#19]
AtlasQuest - Fan Update

https://www.curseforge.com/wow/addons/atlas-quest-fan-update

**Comment by Hoizame** [comment]
Atlas integration is coming when I have the time :)

**Comment by mi5t** [comment]
Thank you so much for upcoming Atlas integration.

**Comment by beren12** [comment]
So, it's been almost 18 months. I love what you have done, but is there any chance of this getting Atlas integration? I would so love it :-) It takes up 2 spots on my minimap so I can see the atlas quest stuff and quest items, or the loot. Great job keeping this going though!
