### ISSUE TITLE
Season 2 PVP weapons are showing the cost of current Season 3 weapons, and Season 3 weapons are showing the current cost of Season 2 weapons

### ISSUE THREAD

**Issue by amitbd33** [Hoizame/AtlasLootClassic#192]
**Module:**  PVP
**Category:** Arena
**Loottable:** All Weapons for Season 2 + 3
**Items:** Season 2 vs Season 3 PVP weapons

**Additional context**
Season 2 and 3 PVP weapon costs (arena points) are flipped.

**Comment by Mard35** [comment]
Now after last update both s2 and s3 has 50% discount

**Comment by Hoizame** [comment]
I added a vendor scanner with last development push that updates prices inside AtlasLoot after visiting a related vendor

But that needs some testing
