### ISSUE TITLE
Season 1 honor cost doesn't show correctly compared to vendors.

### ISSUE THREAD

**Issue by trondii** [Hoizame/AtlasLootClassic#194]
So I was farming honor cause I really thought the Season 1 weapons were cheap  9k honor for 2h S1 weapon, it said so on the wowhead. and after i reached the honor I was super super excited, only to find out that   Atlasloot was lying all along, S1 weapons didn't have the low cost like it said.     

And if it has that low cost where could i buy them for that low price hmmm?`

so i think the addon is lying

**Comment by tbrad86** [comment]
If you could update the cost of PVP items based on the recent changes Blizzard made that would be awesome. Most marks that cost 20 are now 10 and 40 are 20 etc. and the honor points are wrong on say "Vindicator's Leather Bracers" for example.

**Comment by illutian** [comment]
Yep...all of S1's weapons are double what AtlasLoot says they'll cost, and don't require Marks.

**Comment by NNCSavage** [comment]
I do not know how to add LUA files. But these two should update most PVP items + add the Battlemaster trinkets to S3

AtlasLootClassic > Data Folder
[VendorPrice.txt](https://github.com/Hoizame/AtlasLootClassic/files/8227204/VendorPrice.txt)
AtlasLootClassic_PVP
[data-tbc.txt](https://github.com/Hoizame/AtlasLootClassic/files/8227210/data-tbc.txt)

**Comment by Hoizame** [comment]
#192
