### ISSUE TITLE
Season 3 honor items (boots, bracers, necks) does not match vendor

### ISSUE THREAD

**Issue by DBFBlackbull** [Hoizame/AtlasLootClassic#195]
Atlas loot show the double amout of marks needed to buy bracers, boots and neck compared to vendor.

for instance, the boots is listed as costing 40 eye of the storm mark, while in reality they only cost 20
The neck is listed as costing 10 warsong gulch marks, but only cost 5

**Comment by Hoizame** [comment]
#192
