### ISSUE TITLE
Please add Zul'Aman patch, Badge of Justice items 

### ISSUE THREAD

**Issue by Jorvanus** [Hoizame/AtlasLootClassic#196]
ZA is currently on PTR, along with new badge items.  The badge items are not in atlasloot.  If these could be added, that would be great.

**Comment by NNCSavage** [comment]
AtlasLoot_Collections:
[data.txt](https://github.com/Hoizame/AtlasLootClassic/files/8232411/data.txt)
AtlasLootClassic > Data
[VendorPrice.txt](https://github.com/Hoizame/AtlasLootClassic/files/8232429/VendorPrice.txt)

rename to .lua and replace

Then there should be a new BoJ vendor Phase 4 in the dropdown for Collections

**Comment by Hoizame** [comment]
I will update missing data and update vendor prices on the weekend

**Comment by johnolos** [comment]
@Hoizame Lots of people probably waiting on this. Hope you have time this weekend. Especially now since ZA is announced.

**Comment by Jorvanus** [comment]
> @Hoizame Lots of people probably waiting on this. Hope you have time this weekend. Especially now since ZA is announced.

yeah big time, hope you get some time this weekend also.  :-)

**Comment by Balanarior** [comment]
data.txt seems to be 500 lines shorter than old one, collections are missing. can you check and update it please

**Comment by NNCSavage** [comment]
I just opened both and they are the same length - 2059 lines

**Comment by NNCSavage** [comment]
I don't mind at all - I had an accessories category but also broke them out singly in case that helped people. Just having the gear in the addon was enough for me but I always appreciate other viewpoints

**Comment by Valmere** [comment]
> AtlasLoot_Collections: [data.txt](https://github.com/Hoizame/AtlasLootClassic/files/8232411/data.txt) AtlasLootClassic > Data [VendorPrice.txt](https://github.com/Hoizame/AtlasLootClassic/files/8232429/VendorPrice.txt)
> 
> rename to .lua and replace
> 
> Then there should be a new BoJ vendor Phase 4 in the dropdown for Collections

few issues here, 2 "Back" sections, the cloak is also in "accessories", plate belt in the mail section, and as others have said there really isn't a need to have the same items listed under multiple categories.

**Comment by Senjiu** [comment]
Just use the second data.lua file from 2 posts before yours, where I fixed those issues. :)

**Comment by trying-to-function** [comment]
I think #198 should close this issue.
