### ISSUE TITLE
Can't swap between classic and tbc

### ISSUE THREAD

**Issue by Aranoa** [Hoizame/AtlasLootClassic#197]
I understand that to swap from classic content to tbc content I need to click on the WoW symbol at the top however whenever I click it nothing changes and I can only see the classic content and none of the outland and other tbc content. Has anyone else experienced this or is there a particular setting I've clicked accidentally that's stopping me from swapping between the two?

**Comment by Hoizame** [comment]
Use the BC version not the classic version should fix this :)
