### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by Phatcat** [Hoizame/AtlasLootClassic#20]
Atlasloot and atlasloot enhanced are created and released under the gplv2 license.

Atlasloot classic says on curseforge, at the very top, that it's released under gplv2, and it even says a copy of that license will be in the folder (It used to be, I have the old Atlasloot form 1.12 and that one has a gpl-v2.txt file. Atlasloot classic however, has another file, inside the documentation folder, called 'license' which simply states that 'all rights reserved'.

There are several issues here. First issue. You must include the license file when distributing a gplv2 project, otherwise you are breaking the license. Furthermore, you cannot simply write in extra clauses that 'all rights are reserved' as this also breaks with the gpl license.

Please remove your weird custom 'license' and include the proper gplv2 license so everyone can see and know that they are allowed to copy, modify and distribute this addon.

**Comment by Phatcat** [comment]
![image](https://user-images.githubusercontent.com/1907820/65330316-99aa8500-dbba-11e9-8584-1926ea779337.png)

**Comment by Hoizame** [comment]
Forgot to change that when switching packager thanks
