### ISSUE TITLE
Wrong Item in Season 3 Weapons Two-Handed

### ISSUE THREAD

**Issue by Jorvanus** [Hoizame/AtlasLootClassic#205]
PVP, Season 3, Weapons Two Handed

Seasons 2 Gladiators Maul is linked when it should be seasons 3. 

![image](https://user-images.githubusercontent.com/89010934/167046824-c5269f78-9a45-4375-a499-80ff1dc3e0fe.png)

**Comment by Hoizame** [comment]
Is there even a S3 version of this? 
Can't find any.

**Comment by Jorvanus** [comment]
> 

you're right.  Should just be removed from there then.
