### ISSUE TITLE
wotlk

### ISSUE THREAD

**Issue by stpain** [Hoizame/AtlasLootClassic#207]
Hi, will there be a WotLK update to this addon?

**Comment by Hoizame** [comment]
Got my beta invite today so yes im working on it

**Comment by stpain** [comment]
Brilliant thanks - I also just got an invite! Never been chosen for anything before.

**Comment by Firsthunterz** [comment]
I dont know if you have the old AtlasLoot files (3.3.5a) but incase you dont... ill put this here. It at the very least has all the drop locations along with names/IDs of items. Hopefully it might help
[wrathofthelichking.lua.txt](https://github.com/Hoizame/AtlasLootClassic/files/9246073/wrathofthelichking.lua.txt)

**Comment by ZhandPally** [comment]
Hey, just wondering if there's an update on this. I know it's probably a lot of work, but just wanting to see. Much appreciated!

**Comment by Hoizame** [comment]
wotlk branch ;)
https://github.com/Hoizame/AtlasLootClassic/tree/wotlk

**Comment by stpain** [comment]
Will this include crafting items?

**Comment by Hoizame** [comment]
not at first beta as my formatting is not done jet

**Comment by Korenn** [comment]
Prepatch launched now, no new version?

**Comment by cwilson21** [comment]
Pretty sure with the coming of pre-patch, the timed chests in ZA have changed, at least the 4th one and the bear is no longer awarded.
