### ISSUE TITLE
Inscription for WOTLK

### ISSUE THREAD

**Issue by Forthehorde2022** [Hoizame/AtlasLootClassic#210]
there does not appear to have inscription in Atlas loot - under crafting

possible to get this added ?

using version [v3.0.0-beta2](https://www.curseforge.com/wow/addons/atlaslootclassic/files/3961045)

**Comment by Hoizame** [comment]
Crafting and Collections are planned for next version.

**Comment by Hoizame** [comment]
added with beta3
