### ISSUE TITLE
Colored skill numbers are not full visible

### ISSUE THREAD

**Issue by voxan-dev** [Hoizame/AtlasLootClassic#211]
**Lua error**
no error
**Describe the bug**
The numbers of skill, on which the crafted item turn to yellow, green or gray are not full visible. In the german version it this for 
- Blacksmithing
- Enchanting
- Engineering
- Leatherworking
- Jewelcrafting
- Inscription
Probably other at other languages.
**To Reproduce**
Look every Profession.
**Expected behavior**
Numbers should always be full visible
**Screenshots**
![image](https://user-images.githubusercontent.com/38700040/188308266-9e552f8f-f493-4f99-83b9-468cff7bcda8.png)
possible solution:
![image](https://user-images.githubusercontent.com/38700040/188308398-77d6244b-47e6-4ed6-9615-02dd110db18a.png)
![image](https://user-images.githubusercontent.com/38700040/188308407-56f1c38a-3dab-4cf5-974a-6a4ba02ca456.png)

**Additional context**
I suggest a solution like Herbalism. There is no need to have the Profession as a string at every item. And it seems that the long string is the problem.

**Comment by voxan-dev** [comment]
AtlasLootClassic/Data/Profession.lua
line 20 - 34
replace the strings with shorter names works for me. are there any other dependecies?
![image](https://user-images.githubusercontent.com/38700040/188325086-c406a1eb-d95a-45dd-a719-2856a700348a.png)

**Comment by Hoizame** [comment]
Nein das sollte reichen
Ich bau ein, dass der berufsname automatisch gekürzt wird wenn er zu lange ist

**Comment by Hoizame** [comment]
Mit release v3.0.0 sollte das besser sein oder?

**Comment by voxan-dev** [comment]
Leider nein. Zwar wird der Name gekürzt, aber nicht genug. Meiner Meinung nach braucht es an dieser Stelle sowieso keine Berufsbezeichnung. Die steht ja bereits bei "Unterkategorie". Aber wird sicher auch seine Gründe haben.

![image](https://user-images.githubusercontent.com/38700040/189456370-91fa2fa7-0005-4e2d-9cf0-4e6ad80b1362.png)

**Comment by Hoizame** [comment]
Ich benutz den Text ja nicht nur im Crafting modul ;), hab aber auch gemerkt, dass das Textfeld zu kurz war das hab ich grade geändert.
Damit sollte es jetzt dann eigentlich klappen hats zumindest in meinem Test. (Namen sind jetzt englisch aber das ja egal)
![image](https://user-images.githubusercontent.com/45636893/189456749-01b88bb9-5035-43bf-bbd9-2327aeb94831.png)

**Comment by voxan-dev** [comment]
Ja das war natürlich nur eine spontane Idee. Ich habe gar keine Überblick über die ganzen Abhängigkeiten. Dann warte ich mal auf den n#chsten Commit und ziehe mir den.

**Comment by voxan-dev** [comment]
Sieht gut aus. Danke dir.
