### ISSUE TITLE
no wotlk loot

### ISSUE THREAD

**Issue by Bugaloon** [Hoizame/AtlasLootClassic#213]
i download latest version just now, no update since may 10, no wotlk item

when will wotlk item be added?

**Comment by Hoizame** [comment]
BETA not the last normal release...
https://www.curseforge.com/wow/addons/atlaslootclassic/files/3965795

**Comment by Bugaloon** [comment]
why would you hide update, put on main page silly

**Comment by Hoizame** [comment]
Thats how curseforge work not my desicion
