### ISSUE TITLE
Curseforge App Issue

### ISSUE THREAD

**Issue by Wyr3d** [Hoizame/AtlasLootClassic#227]
Curseforge has this addon flagged as:

This might be corrupt, "belongs to Retail" so you might wanna fix that.

**Comment by Hoizame** [comment]
I cant do anything there as its a curseforge thing.
Maybe you are not using the beta release and it detects the current release version as corrupt as its still for bcc only.

**Comment by Wyr3d** [comment]
Well, it's fixed with today's update anyway XD
