### ISSUE TITLE
Missing Level Ranges for Pre-TBC dungeons

### ISSUE THREAD

**Issue by Vealor** [Hoizame/AtlasLootClassic#229]
**Lua error**
N/A

**Describe the bug**
Missing level ranges and minimum entry for most of the pre-TBC dungeons.  Everything for TBC and WotLK are there.

**To Reproduce**
![image](https://user-images.githubusercontent.com/6099022/189409576-e2fb0998-355a-4217-ba3f-09ea3bc94180.png)

**Expected behavior**
Should be complete like it is for TBC (screenshot)
![image](https://user-images.githubusercontent.com/6099022/189409470-06495fb6-0952-4744-9f26-a4d3b3671c3b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6099022/189409264-f4ef654a-ef9f-443b-94da-914a45fb3a10.png)

**Additional context**

**Comment by Hoizame** [comment]
Thanks, fixed for next version
