### ISSUE TITLE
v1.1.12 Not working on Mac Client

### ISSUE THREAD

**Issue by Chudomira** [Hoizame/AtlasLootClassic#23]
Tried all versions of AtlasLootClassic and beta on my mac client and have been unable to get it to work even if I messed around with filepaths/folders which has fixed this issue in the past with other add-ons.

![Screen Shot 2019-09-22 at 18 41 26](https://user-images.githubusercontent.com/55661012/65389564-a8cf3580-dd68-11e9-8a78-2341cb56b9f0.png)
![Screen Shot 2019-09-22 at 18 41 18](https://user-images.githubusercontent.com/55661012/65389565-aa98f900-dd68-11e9-9cbd-c0e5a33e68a0.png)

![Screen Shot 2019-09-22 at 18 43 29](https://user-images.githubusercontent.com/55661012/65389600-ee8bfe00-dd68-11e9-858e-edef6adbe84e.png)

**Comment by Hoizame** [comment]
Hey please move the folders out of the "AltasLootClassic-v1.1.12-classic" Folder :)

**Comment by Chudomira** [comment]
Thanks, that fixed the issue.
