### ISSUE TITLE
Glyph of Starfire missing from inscription

### ISSUE THREAD

**Issue by SvenskNavi** [Hoizame/AtlasLootClassic#230]
Feel free to ignore if there's something I don't know since I'm new to Wrath, but it looks like Glyph of Starfire is missing from the list of druid glyphs in the inscription subcategory. Looks like it's in the game, learnable at 220. https://www.wowhead.com/wotlk/spell=56959/glyph-of-starfire

**Comment by Hoizame** [comment]
Yep was missing, added for next version. Thanks!
