### ISSUE TITLE
Latest update on login error (3.0.1)

### ISSUE THREAD

**Issue by Translitdk** [Hoizame/AtlasLootClassic#233]
**Lua error**
```
5x ...Ons\AtlasLootClassic_DungeonsAndRaids\data-wrath.lua:5058: invalid option in `format'
[string "=[C]"]: in function `format'
[string "@AtlasLootClassic_DungeonsAndRaids\data-wrath.lua"]:5058: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@AtlasLootClassic\Loader.lua"]:202: in function `LoadModule'
[string "@AtlasLootClassic\Data\AutoSelect.lua"]:1083: in function `RefreshOptions'
[string "@AtlasLootClassic\Loader.lua"]:139: in function `func'
[string "@AtlasLootClassic\AtlasLoot-1.3000001.lua"]:42: in function <AtlasLootClassic\AtlasLoot.lua:34>

Locals:
(*temporary) = "%Попыток осталось"
(*temporary) = "1-24"
```
**Describe the bug**
Error happens on the login with latest update (v3.0.1) on ruRU locale. Didn't test on enGB so can't really say if it's really region dependant
**To Reproduce**
Just login
**Expected behavior**
No error
**Screenshots**
![BugSack](https://i.imgur.com/lkXreU8.png)
**Additional context**

**Comment by Hoizame** [comment]
That was an error in the translation of ["%s Attempts left"] as it was changed into ["%Попыток осталось"]
Can you please check if https://www.curseforge.com/wow/addons/atlaslootclassic/localization/languages/98/phrases#420751 is correct translated now?

**Comment by Translitdk** [comment]
yeah i just checked by myself 1 min ago and came back but you already alswered.
![](https://i.imgur.com/6jxLiyy.png)
changing to ```
AL["%s Attempts left"] = "%s Попыток осталось"```
fixes it
