### ISSUE TITLE
Incorrect Profession Skill Levels

### ISSUE THREAD

**Issue by Firsthunterz** [Hoizame/AtlasLootClassic#236]
Not sure if its a bug or if there just temporary but most of the WotLK professions are showing they require 375 which isnt right. Example is Armor Plated Shotgun which shows as 375 (orange) isnt correct because it requires 450 engi

**Comment by wlfbck** [comment]
There are several like these, for example "Smelt Thorium" (and mining it) is 230 now, not 250.
