### ISSUE TITLE
Level of dungeon bosses

### ISSUE THREAD

**Issue by wallrik** [Hoizame/AtlasLootClassic#24]
**Is your feature request related to a problem? Please describe.**
I see the level range on the list of dungeons, but I like to judge the minimum level for tanking by the level of the end boss.

**Describe the solution you'd like**
Is it possible to also state what level each boss is for dungeons?

**Comment by Hoizame** [comment]
That would be no problem but I dont know whats the best way to display it :D

**Comment by Hoizame** [comment]
Maybe that way?
![image](https://user-images.githubusercontent.com/45636893/65921362-4f0ee100-e3e2-11e9-8d61-c978a43c571d.png)

**Comment by wallrik** [comment]
That works very well! It would be nice to have as an option as it's not _that_ useful once you reach 60 :) But I would love that when leveling up. Especially as a tank, to know what I'm up against ^^

**Comment by Hoizame** [comment]
A option is in and I think as standard it should be set disabled

**Comment by Hoizame** [comment]
Added with v1.2.1
