### ISSUE TITLE
Nexus normal missing from AtlasLootClassic Wrath version. 

### ISSUE THREAD

**Issue by Rorthron** [Hoizame/AtlasLootClassic#241]
Nexus shows up only as Heroic. There is no normal option from the drop down. 

![image](https://user-images.githubusercontent.com/44713088/192350287-d19e46dd-cb88-4b1d-bf2e-5128fb48fa9d.png)

**Comment by Ruffelsx** [comment]
Isn't that just a heroic only boss? The other bosses show loot for normal mode

**Comment by Hoizame** [comment]
Yes should be a heroic only boss

**Comment by Rorthron** [comment]
Yes, you are correct. I was confused as they showed out of order. Apologies
