### ISSUE TITLE
Spell Power food missing from Wrath Cooking

### ISSUE THREAD

**Issue by adispen** [Hoizame/AtlasLootClassic#242]
Noticed that there was no Spell Power section under cooking. These recipes include:

[Shoveltusk Steak](https://www.wowhead.com/wotlk/spell=45550/shoveltusk-steak)
[Smoked Salmon](https://www.wowhead.com/wotlk/spell=45564/smoked-salmon)

[Tender Shoveltusk Steak](https://www.wowhead.com/wotlk/spell=45556/tender-shoveltusk-steak)
[Firecracker Salmon](https://www.wowhead.com/wotlk/spell=45568/firecracker-salmon)

**Comment by Hoizame** [comment]
Thanks, added for next version that gets released later today

**Comment by adispen** [comment]
Appreciate it, just did a full sweep of the cooking section #244

**Comment by Hoizame** [comment]
Its merged and v3.0.3 is pushed for release thanks :)
