### ISSUE TITLE
Disabling tooltip

### ISSUE THREAD

**Issue by puschie286** [Hoizame/AtlasLootClassic#245]
Im trying to disable all tooltip modifications from atlasloot - even after disable all points under "ToolTip" everything is shown in the tooltip as before

![image](https://user-images.githubusercontent.com/2429036/193159707-111795c4-69a2-438b-9b0d-44d168060b57.png)
![image](https://user-images.githubusercontent.com/2429036/193159762-d11caf08-d57e-4f5f-830e-507ffc13e781.png)

**Comment by Hoizame** [comment]
Thats part of the Source addon in the atlasloot options just disable it there
