### ISSUE TITLE
invalid option in `format'

### ISSUE THREAD

**Issue by Kilmatar** [Hoizame/AtlasLootClassic#246]
Date: 2022-09-30 14:21:45
ID: 1
Error occured in: Global
Count: 1
Message: ...Ons\AtlasLootClassic_DungeonsAndRaids\data-wrath.lua line 5061:
   invalid option in `format'
Debug:
   [string "=[C]"]: format()
   [string "@AtlasLootClassic_DungeonsAndRaids\data-wrath.lua"]:5061: in main chunk
   [string "=[C]"]: LoadAddOn()
   [string "@AtlasLootClassic\Loader.lua"]:202: LoadModule()
   [string "@AtlasLootClassic\Data\AutoSelect.lua"]:1083: RefreshOptions()
   [string "@AtlasLootClassic\Loader.lua"]:139: func()
   [string "@AtlasLootClassic\AtlasLoot.lua"]:42:
      AtlasLootClassic\AtlasLoot.lua:34
Locals:
(*temporary) = "Включает добычу из %а"
(*temporary) = "1-24"

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  WowheadLooter, v30400
  Ace3, vr1292
  AdvancedInterfaceOptions, v1.7.2-2-g3742126
  AlreadyKnown, v1.46
  Altoholic, v2.5.008
  Atlas, vv1.51.06
  AtlasLootClassic, vv3.0.3
  AtlasLootClassicDungeonsAndRaids, vv3.0.3
  DataStore, v2022.06.05
  DataStoreCharacters, v2022.06.05
  BlizRuntimeLib_ruRU v3.4.0.30400 <none>
  (ck=16b)

==============
Just logging to game

**Comment by Hoizame** [comment]
Translation error from https://www.curseforge.com/wow/addons/atlaslootclassic/localization/languages/98/phrases
Should be fixed with next release.

**Comment by Hoizame** [comment]
Thanks for the report, should be fixed with v3.0.4 see also #250
