### ISSUE TITLE
Jewelcrafting: Prismatic Gems Missing

### ISSUE THREAD

**Issue by AndreWaehlisch** [Hoizame/AtlasLootClassic#253]
**Module:** Crafting
**Category:** Jewelcrafting
**Loottable:** Gems - Prismatic
**Items:** All

**Additional context**
Prismatic gems seem to be missing, see here: https://www.wowhead.com/wotlk/items/gems/prismatic

**Comment by Hoizame** [comment]
Thanks for the Info its added with v3.0.5 from adispen with pr #257
