### ISSUE TITLE
Pattern: Dragonscale Ammo Pouch

### ISSUE THREAD

**Issue by AndreWaehlisch** [Hoizame/AtlasLootClassic#255]
**Module:** Factions
**Category:** The Kalu'ak
**Loottable:** Honored
**Items:** Pattern: Dragonscale Ammo Pouch

**Additional context**
The following recipe seems to be missing: https://www.wowhead.com/wotlk/item=44511/pattern-dragonscale-ammo-pouch

**Comment by Hoizame** [comment]
Thanks, added with v3.0.5
