### ISSUE TITLE
Boss Earthcaller Halmgar

### ISSUE THREAD

**Issue by UnfoldedDeep** [Hoizame/AtlasLootClassic#26]
In the dungeon "Razorfen Kraul" there is a boss named "Earthcaller Halmgar". He is a rare spawn, can you please do this little icon beside his name? I was confused in not finding him until I googled and found out he is a rare spawn, thank you.

Thanks for making our wow lives easier with this addon ;)
Best wishes

**Comment by Hoizame** [comment]
done thanks :)
