### ISSUE TITLE
AtlasLoot opens Naxx 40 while in Naxx 10/25

### ISSUE THREAD

**Issue by tcprescott** [Hoizame/AtlasLootClassic#260]
AtlasLoot is defaulting to original Naxx 40 loot when you open AtlasLoot inside WOTLK's Naxx

To reproduce, open AtlasLoot while in WOTLK Naxxramas.  Opening the appropriate 10 or 25 man version of Naxxramas is what is expected.

**Comment by DarkInos** [comment]
Yep.. opening AtlasLoot in Wotlk "folder" opens loot for 60lvl Naxx.
Got to switch between Wotlk and Burning Crusade and back to get Naxx 80 loot.

**Comment by Hoizame** [comment]
This should be fixed now with v3.0.6

**Comment by DarkInos** [comment]
Open this up again.
Not solved with the new 3.0.6
If you are Inside Naxx, and open Atlas loot, it will open 60lvl one instantly, got to switch between datadiscs to "reset" and allow you to see 80lvl one.

**Comment by tcprescott** [comment]
Can confirm, the bug was still present in 3.0.6.
