### ISSUE TITLE
Missing Venomhide Ravasaur and Sea Turtle in Wrath mounts

### ISSUE THREAD

**Issue by silverhawke249** [Hoizame/AtlasLootClassic#262]
**Module:** AtlasLoot Collections (WotLK)
**Category:** Mounts
**Loottable:** Quest (Venomhide Ravasaur), Fishing (Sea Turtle)
**Items:** 46102 (Venomhide Ravasaur), 46109 (Sea Turtle)

**Comment by Hoizame** [comment]
added with v3.0.7
