### ISSUE TITLE
Updated and it broke...

### ISSUE THREAD

**Issue by niqht1** [Hoizame/AtlasLootClassic#274]
I can't remember for sure what version I was on, but just came back to the game for LK during the bonus XP month.. so recent.
I updated to 3.0.7 the usual copy over the old way and when I loaded it is completely broke. 

**AtlasLoot version**
3.0.7

**Lua error**
Message: ...erface\AddOns\AtlasLootClassic\Addons\Favourites.lua:252: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue Oct 18 20:13:55 2022
Count: 1
Stack: ...erface\AddOns\AtlasLootClassic\Addons\Favourites.lua:252: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Interface\AddOns\AtlasLootClassic\Addons\Favourites.lua"]:252: in function `UpdateDb'
[string "@Interface\AddOns\AtlasLootClassic\Addons\Favourites.lua"]:276: in function `func'
[string "@Interface\AddOns\AtlasLootClassic\AtlasLoot.lua"]:42: in function <Interface\AddOns\AtlasLootClassic\AtlasLoot.lua:34>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

-----

Message: ...erface\AddOns\AtlasLootClassic\Addons\Favourites.lua:333: attempt to index field 'activeList' (a nil value)
Time: Tue Oct 18 20:28:46 2022
Count: 1
Stack: ...erface\AddOns\AtlasLootClassic\Addons\Favourites.lua:333: attempt to index field 'activeList' (a nil value)
[string "@Interface\AddOns\AtlasLootClassic\Button\Button.lua"]:760: in function `SetType'
[string "@Interface\AddOns\AtlasLootClassic\Button\Button.lua"]:727: in function `SetContentTable'
[string "@Interface\AddOns\AtlasLootClassic\GUI\ItemFrame.lua"]:199: in function `Refresh'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:191: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:43>
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:947: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:90: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:137: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:914: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:90: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_Select.lua"]:137: in function `SetData'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:889: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
...
[string "@Interface\AddOns\AtlasLootClassic\Loader.lua"]:166: in function `LoadModule'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:821: in function `ButtonOnClick'
[string "@Interface\AddOns\AtlasLootClassic\GUI\Template_DropDown.lua"]:159: in function `SetSelected'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:247: in function <Interface\AddOns\AtlasLootClassic\GUI\GUI.lua:245>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\AtlasLootClassic\GUI\GUI.lua"]:1031: in function `Toggle'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:20: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Core\SlashCommands.lua"]:58: in function `Run'
[string "@Interface\AddOns\AtlasLootClassic\MiniMapButton.lua"]:51: in function `OnClick'
[string "@Interface\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals: self = AtlasLoot_Button_1 {
 0 = <userdata>
 ItemLvl = 80
 RawName = "Emblem of Triumph"
 SetContentTable = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:604
 GetSecTypeFunctions = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:811
 ItemID = 47241
 formatTab = <table> {
 }
 SetPreSet = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:594
 phaseIndicator = AtlasLoot_Button_1_phaseIndicator {
 }
 secButton = AtlasLoot_Button_1_secButton {
 }
 highlightBg = AtlasLoot_Button_1_highlightBg {
 }
 background = AtlasLoot_Button_1_background {
 }
 favourite = AtlasLoot_Button_1_favourite {
 }
 SetType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:751
 Clear = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:541
 GetTypeFunctions = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:807
 SetDifficultyID = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:799
 extra = AtlasLoot_Button_1_extra {
 }
 __atlaslootinfo = <table> {
 }
 AddEnhancedDescription = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:935
 SetExtraType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:780
 completed = AtlasLoot_Button_1_completed {
 }
 SetNpcID = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:803
 name = AtlasLoot_Button_1_name {
 }
 overlay = AtlasLoot_Button_1_overlay {
 }
 factionIcon = AtlasLoot_Button_1_factionIcon {
 }
 SetSecType = <function

-----

Message: ...erface\AddOns\AtlasLootClassic\Addons\Favourites.lua:333: attempt to index field 'activeList' (a nil value)
Time: Tue Oct 18 20:29:46 2022
Count: 4
Stack: ...erface\AddOns\AtlasLootClassic\Addons\Favourites.lua:333: attempt to index field 'activeList' (a nil value)

Locals: 

**Describe the bug**
Most of the time will not show item lists. Will show normal/heroic and multiple boss selections highlighted at the same time.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Went back to 3.06 and no difference.
Deleted all the folders and reloaded WoW, then reinstalled 3.0.7 and reload again and no change.
Possibly some stored conflict?
I will play with it some more, but I don't have time at the moment

**Comment by ForsakenNGS** [comment]
> Deleted all the folders and reloaded WoW
Did that include the SavedVariables? I'd assume there's your problem. You should try:
- Quit WoW
- Delete or move your `World of Warcraft/_classic_/WTF/Account/YOURACCOUNT/SavedVariables/AtlasLootClassic.lua`
- Start WoW and check if the issue persists
