### ISSUE TITLE
Target of Target Tooltip issues

### ISSUE THREAD

**Issue by Reudig** [Hoizame/AtlasLootClassic#3]
**Lua error**
Message: Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:126: Usage: UnitGUID("unit")
Time: Wed Aug 28 20:49:56 2019
Count: 22
Stack: Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:126: Usage: UnitGUID("unit")
[C]: ?
Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:126: in function <Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:124>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:291: in function `UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:277: in function <Interface\FrameXML\UnitFrame.lua:264>

Locals: (*temporary) = nil

**Describe the bug**
LUA Error pops up whenever I mouseover the target of target unit frame and I'm not the target of target.

**To Reproduce**
LUA Error pops up whenever I mouseover the target of target unit frame and I'm not the target of target.

**Expected behavior**
No error ... don't even know what AtlasLoot has to do with that tooltip.

**Screenshots**

**Additional context**
Using TukUI Classic to modify tooltips.

**Comment by Hoizame** [comment]
Hey thanks for report thats something to test some parts for a planed feature
Should be fixed with last beta thanks!
