### ISSUE TITLE
Sort Favorites List by Instance

### ISSUE THREAD

**Issue by Elatio** [Hoizame/AtlasLootClassic#31]
Would it be possible to add a feature where i can sort my favorites list by what  Instance they appear? e.g. when i have added lots of favorites can i view them like this -

Strath
    Helm
   Shoulders

Scholo
    Gloves
    Belt
    Ring

BRS
   Legs
   Waist 

etc... 

It would make it a lot easier to see where i need to go to get the items i need.

Thanks in advance!

**Comment by Hoizame** [comment]
The next step in this way is add droplocations into ToolTips. Maybe I add something like that after.

**Comment by Elatio** [comment]
Great, thank you for your response! :)

**Comment by Asaelem** [comment]
> The next step in this way is add droplocations into ToolTips. Maybe I add something like that after.

I was actually just going to post a comment about this haha. I would love for this to be implemented!

**Comment by Hoizame** [comment]
Added source info into tooltips with v1.3.0

**Comment by Lupe4js** [comment]
This is a really needed feature.
We need to be able to create list of Items ("resto gear" / "dps gear" ....) and to be able to attribute items to this list.
Then we should be able to watch those lists and remove items in it.

This is my main use of AtlasLoot usually.
