### ISSUE TITLE
Urok Doomhowl's does not drop Rosewine Circle.

### ISSUE THREAD

**Issue by ribonuge** [Hoizame/AtlasLootClassic#34]
**Module:** 
Dungeons and Raids
**Category:**
Lower Blackrock Spire
**Loottable:**
Urok Doomhowl
**Items:**
Rosewine Circle
**Additional context**
This item drops from War Master Voone, not Urok Doomhowl!

**Comment by Hoizame** [comment]
fixed for next release thanks!
