### ISSUE TITLE
Missing addon on Mini map after recent update

### ISSUE THREAD

**Issue by Wild1g** [Hoizame/AtlasLootClassic#37]
**Lua error**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nodashipl** [comment]
I also have this issue. Dont know how to access it now

**Comment by Hoizame** [comment]
Did you restart the game after updating it and are all the AtlasLootClassic_XXX folders inside the Addons folder?

**Comment by nodashipl** [comment]
Ahh i feel silly you are correct after restarting wow it was fixed. My fault
