### ISSUE TITLE
Instance "Uldaman"

### ISSUE THREAD

**Issue by UnfoldedDeep** [Hoizame/AtlasLootClassic#40]
On the instance map is a number 2 but in the listing to the right is the guy for a quest missing.
The numbers 5 and 6 the same. At 5 I don't know what there is but 6 must be the enchanter trainer.

**Comment by Blackwidow-sudo** [comment]
I added number 5 (Boss for Mage Quest), but the others are just NPCs that dont drop something.

I also added [Conspicuous Urn](https://classic.wowhead.com/object=125477/conspicuous-urn) (mapmarker 1) which holds [Shattered Necklace Topaz](https://classic.wowhead.com/item=7671/shattered-necklace-topaz).
But with that i found out that for many of the questitems in uldaman, the source shown on tooltip is incorrect.
- [Gni'kiv Medallion](https://classic.wowhead.com/item=7740/gnikiv-medallion) shows "Uldaman - Trash" as source but should be [Baelog's Chest](https://classic.wowhead.com/object=123329/baelogs-chest)
- [Shattered Necklace Ruby](https://classic.wowhead.com/item=7669/shattered-necklace-ruby) shows [Baelog's Chest](https://classic.wowhead.com/object=123329/baelogs-chest) as source but should be [Shadowforge Cache](https://classic.wowhead.com/object=113757/shadowforge-cache)
- [Tablet of Will](https://classic.wowhead.com/item=5824/tablet-of-will) shows [Conspicuous Urn](https://classic.wowhead.com/object=125477/conspicuous-urn) as source but should be [Tablet of Will](https://classic.wowhead.com/object=142088/tablet-of-will)
- [Shattered Necklace Topaz](https://classic.wowhead.com/item=7671/shattered-necklace-topaz) which i added, shows no source and should be [Conspicuous Urn](https://classic.wowhead.com/object=125477/conspicuous-urn)
