### ISSUE TITLE
ICC Phase 4 pre-release

### ISSUE THREAD

**Issue by Luffty** [Hoizame/AtlasLootClassic#401]
V3.1.3 for game version 3.4.2.

133x AtlasLootClassic/Data/Companion.lua:674: table index is nil
[string "@AtlasLootClassic/Data/Companion.lua"]:674: in function <AtlasLootClassic/Data/Companion.lua:669>
[string "@AtlasLootClassic/Data/Companion.lua"]:682: in function <AtlasLootClassic/Data/Companion.lua:677>

Locals:
typ = "MOUNT"
(for index) = 1
(for limit) = 7
(for step) = 1
i = 1
creatureID = nil
(*temporary) = <table> {
 32818 = true
 7567 = true
 20472 = true
 33226 = true
 32589 = true
 7382 = true
 21018 = true
 10598 = true
 7394 = true
 26119 = true
 23909 = true
 7381 = true
 7565 = true
 7383 = true
 21064 = true
 7389 = true
 7395 = true
 21009 = true
 21055 = true
 7562 = true
 7380 = true
 21010 = true
 15698 = true
 7384 = true
 7553 = true
}
(*temporary) = 1
(*temporary) = "table index is nil"
COLLECTED_COMPANIONS = <table> {
 32818 = true
 7567 = true
 20472 = true
 33226 = true
 32589 = true
 7382 = true
 21018 = true
 10598 = true
 7394 = true
 26119 = true
 23909 = true
 7381 = true
 7565 = true
 7383 = true
 21064 = true
 7389 = true
 7395 = true
 21009 = true
 21055 = true
 7562 = true
 7380 = true
 21010 = true
 15698 = true
 7384 = true
 7553 = true
}

Cannot open/use atlasloot, and bugsack reports bugs squashed every few seconds, until I disable atlasloot core and reload.

Became a problem during ICC pre-release, and the patch changes within.

**Expected behavior**

**Screenshots**

Based on the lua strings, I assume it has to do with the "new" collections tab for mounts, pets, and toys ingame (shift+p).

**Comment by Iowerth** [comment]
Before posting try to search duplicates - https://github.com/Hoizame/AtlasLootClassic/issues/399

**Comment by Luffty** [comment]
Thank you, it resolved the issue :)
And yes, I could have looked into the previous posts in detail, but settled for skimming titles
