### ISSUE TITLE
Item tooltips to show where this item is droped

### ISSUE THREAD

**Issue by jindaxia** [Hoizame/AtlasLootClassic#43]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Item tooltips to show where this item is droped，It‘s usefull I think

**Additional context**

**Comment by Hoizame** [comment]
![image](https://user-images.githubusercontent.com/45636893/66686414-ae40e100-ec7f-11e9-8960-95931028e296.png)

**Comment by jindaxia** [comment]
So,  there's something wrong with my addon?

**Comment by Hoizame** [comment]
Oh no sry looks lkke my text got cut.
This is a preview of what Im working on

**Comment by jindaxia** [comment]
OK， thanks

**Comment by Hoizame** [comment]
Added with version 1.3.0

**Comment by Qrokqt** [comment]
how do i turn this off

**Comment by Hoizame** [comment]
Options
