### ISSUE TITLE
I ask for the improvement of localized translation methods.

### ISSUE THREAD

**Issue by chkmyid** [Hoizame/AtlasLootClassic#48]
**Lua error**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

The phrase key in AtlasLoot.IngeameLocales(ALIL) from the client has a different localized, translated representation that is actually used. How do I translate this part separately? And for example, "Crafting - Blacksmithing - Weapons" is in English because there is no localized translation. I want to improve my AL so that I can use it all without using ALIL.

Finally, the "Show all items" button in the favorites frame does not have a localized phrase key. I need an update on this.

**Comment by chkmyid** [comment]
![WoWScrnShot_1](https://user-images.githubusercontent.com/55096941/66884677-eabc6600-f00c-11e9-8cef-13493778b52f.jpg)
![WoWScrnShot_2](https://user-images.githubusercontent.com/55096941/66884681-edb75680-f00c-11e9-9474-79e6e9c2de2c.jpg)

**Comment by Hoizame** [comment]
Hey thanks for your report.
I switched some translations now and move the Weapons and Armor into the translation namespace for curseforge.
Please report any other translations that are maybe wrong :)

**Comment by chkmyid** [comment]
In addition, please change "Crafting - Cooking - Special"

In my opinion, in the long run, if all of the ALILs are removed and not localized manually, I'd be a little concerned with every word that the user sees that doesn't match perfectly.

Thank you for your hard work.

**Comment by chkmyid** [comment]
![WoWScrnShot_3](https://user-images.githubusercontent.com/55096941/66890961-d4210980-f022-11e9-994e-90a2f1f52e4e.jpg)

**Comment by Hoizame** [comment]
ALIL is using blizzard locals and are mostly used for basic UI things and item descriptions.
Your reports are done
