### ISSUE TITLE
Please check and correct non-localized string.

### ISSUE THREAD

**Issue by chkmyid** [Hoizame/AtlasLootClassic#51]
**Lua error**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![WoWScrnShot_1](https://user-images.githubusercontent.com/55096941/67201292-f232a380-f440-11e9-93ab-e5dd7f18bdd1.jpg)
![WoWScrnShot_2](https://user-images.githubusercontent.com/55096941/67201306-f52d9400-f440-11e9-904b-71e410f20400.jpg)
![3](https://user-images.githubusercontent.com/55096941/67201537-7b49da80-f441-11e9-9bb8-10fa937a8603.jpg)

**Comment by Hoizame** [comment]
Found and fixed the Problem thanks :)

**Comment by chkmyid** [comment]
Thanks
