### ISSUE TITLE
No atlasloot with one character

### ISSUE THREAD

**Issue by Takeanap** [Hoizame/AtlasLootClassic#52]
**Lua error**

**Describe the bug**
Playing with my paladin and other characters the atlasloot icon appears with the minimap but when I play as my hunter character there's no icon near minimap neither there's atlasloot in the addon list. Tried reinstaling it twice, restarted wow after update and still nothing.

It's literally only with the hunter that it won't appear in the minimap circle.

**To Reproduce**

**Expected behavior**

**Screenshots**
[https://imgur.com/a/GSo3gHS](url)
**Additional context**

**Comment by Hoizame** [comment]
Think we found the problem in discord? :)

**Comment by Takeanap** [comment]
We did! /al mmb worked 2nd time I tried! Thanks
