### ISSUE TITLE
PvP Rewards marked as Phase 6

### ISSUE THREAD

**Issue by wallrik** [Hoizame/AtlasLootClassic#56]
Now that people have been able to reach rank 6 and checked the PvP vendors, it appears all the items are available right away.

The R14 weapons marked as Phase 6 are available.
The blue armor sets are available.

https://www.wowhead.com/news=298419/naxx-era-rank-14-weapons-and-revamped-rank-10-pvp-sets-available-in-phase-2-clas

**Comment by Hoizame** [comment]
Fixed for the next release
