### ISSUE TITLE
various minor stuff 

### ISSUE THREAD

**Issue by Nihlo** [Hoizame/AtlasLootClassic#57]
- Panzor in brd is a rare, the rare-icon is missing

- normal pvp rank rewards are missing, stuff which are not part of the sets or weapons. Like:
https://classic.wowhead.com/items/name:first+sergeant's?filter=166;1;0
https://classic.wowhead.com/items/name:senior+sergeant's+insignia?filter=166;1;0
https://classic.wowhead.com/items/name:sergeant's+cloak?filter=166;1;0
https://classic.wowhead.com/item=15197/scouts-tabard
etc

- Avatar of Hakkar in ST has no level, he is 48

- since the latest update some boss lines are buggy. There are empty in the list until you click them and they appear again:

https://ibb.co/w0s5gKV
https://ibb.co/nM5gpbW

happens in more instances

**Comment by Hoizame** [comment]
Thanks fixed all for next release :)
