### ISSUE TITLE
Lua error when hovered over a player.

### ISSUE THREAD

**Issue by Ginnerskov** [Hoizame/AtlasLootClassic#6]
Message: Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:125: Usage: UnitGUID("unit")
Time: Fri Aug 30 00:07:28 2019
Count: 2
Stack: Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:125: Usage: UnitGUID("unit")
[C]: ?
Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:125: in function <Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:123>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:291: in function `UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:277: in function `UnitFrame_OnEnter'
Interface\AddOns\LunaUnitFrames\modules\units.lua:503: in function `OnEnter'
...nterface\AddOns\LunaUnitFrames\modules\highlight.lua:25: in function `OnEnter'
Interface\AddOns\LunaUnitFrames\modules\borders.lua:26: in function `OnEnter'
Interface\AddOns\LunaUnitFrames\modules\units.lua:490: in function <Interface\AddOns\LunaUnitFrames\modules\units.lua:488>

Locals: (*temporary) = nil

**Describe the bug**

Happened when hovering over a player.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Hoizame** [comment]
What version are you using? That should be fixed with the last version v1.1.7-beta1
