### ISSUE TITLE
Missing random enchantments

### ISSUE THREAD

**Issue by laurencei** [Hoizame/AtlasLootClassic#60]
**Version** v.1.4.1

**Issue**
I'm not sure if this a bug, or a feature request - but none of the items that have "random enchantments" seem to display that fact in AtlasLoot. This makes it very deceptive when scrolling through dungeon loot, trying to work out what item you might want to aim for.

Two specific examples:

**Elemental Plate Girdle** - it drops with a random enchantment of something - i.e. Fire Resistance, Nature resistance etc.

![image](https://user-images.githubusercontent.com/1210658/70387824-f8cfa700-19fd-11ea-92a0-d07dccb68961.png)

**Gyths Skull**   - it drops with a random enchantment of something - i.e. Fire Resistance, Nature resistance etc.

![image](https://user-images.githubusercontent.com/1210658/70387834-14d34880-19fe-11ea-9668-c30147ec3bd5.png)

I dont think every possible combination needs to be listed, but just a "**random stat**" or similar line on these items allows people to realise the item is far better than it looks there, and they can go look up more info if needed.

**Comment by Hoizame** [comment]
More a blizzard bug with tooltips.
I changed the way how they get set and a random enchant marker is now shown
![image](https://user-images.githubusercontent.com/45636893/70388954-25150480-19b9-11ea-829f-8cd879bafbc6.png)

**Comment by laurencei** [comment]
@Hoizame - thanks. I tested your PR, and yes, it fixes the issue. Great work! Thanks.
