### ISSUE TITLE
Sort favorites lists alphabetically

### ISSUE THREAD

**Issue by wallrik** [Hoizame/AtlasLootClassic#62]
Would it be possible to sort the dropdown list alphabetically?

I've made favorite lists for every content phase and it would be nice if they were sorted. Now they are all over the place.

![WoWScrnShot_121819_173228](https://user-images.githubusercontent.com/10890923/71104675-79d82c80-21bc-11ea-810a-05ca07f6533d.jpg)

Thank you! :)

**Comment by Hoizame** [comment]
Sure done for next release :)

**Comment by Hoizame** [comment]
Done with v1.4.4
