### ISSUE TITLE
Showing tooltip on item for all wishlists

### ISSUE THREAD

**Issue by cherry-wave** [Hoizame/AtlasLootClassic#63]
Hello, the wishlists are really great but I would like to have an option to be able to see on whichever wishlist an item is. Currently it only shows the tooltip if you really have selected the wishlist. But since I (as a druid) have more than one wishlist I don't want to switch between them to see if the boss' loot is in any wishlist.

**Comment by Hoizame** [comment]
Hey did you try the "Always active" setting in the options?
![image](https://user-images.githubusercontent.com/45636893/71548335-1d8bbe80-29ad-11ea-83ba-4e6df54aa697.png)

**Comment by cherry-wave** [comment]
Oh I am so sorry I didn't saw that. Sorry for opening an unnecessary issue x(

**Comment by Hoizame** [comment]
No problem :)
