### ISSUE TITLE
Update curseforge with translation tables

### ISSUE THREAD

**Issue by woopydalan** [Hoizame/AtlasLootClassic#64]
**Is your feature request related to a problem? Please describe.**
A lot of translations have been added since the last update on Dec. 24. I don't know if you are actively working on new features. If you are just maintaining the addon right now, then it would make sense to update with the translations added on the localization table on curseforge

**Comment by Hoizame** [comment]
Hey yes I work on some things but I will update the addon today with translations thanks for the reminder :)

**Comment by Hoizame** [comment]
done with v1.4.5
