### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Jutty5000** [Hoizame/AtlasLootClassic#7]
**Lua error**
Message: Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:126: Usage: UnitGUID("unit")
Time: Sun Sep  1 05:17:57 2019
Count: 1
Stack: Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:126: Usage: UnitGUID("unit")
[C]: ?
Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:126: in function <Interface\AddOns\AtlasLootClassic\Core\Tooltip.lua:124>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:291: in function `UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:277: in function `UnitFrame_OnEnter'
Interface\AddOns\LunaUnitFrames\modules\units.lua:510: in function `OnEnter'
...nterface\AddOns\LunaUnitFrames\modules\highlight.lua:25: in function `OnEnter'
Interface\AddOns\LunaUnitFrames\modules\borders.lua:26: in function `OnEnter'
Interface\AddOns\LunaUnitFrames\modules\units.lua:497: in function <Interface\AddOns\LunaUnitFrames\modules\units.lua:495>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:266: in function <Interface\FrameXML\SecureHandlers.lua:263>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:322: in function <Interface\FrameXML\SecureHandlers.lua:306>
(tail call): ?

Locals: (*temporary) = nil

**Describe the bug**
Only Occurs with Luna and AtlasLoot, but not just LUF

**To Reproduce**
Have both enabled and hover over ToT

**Comment by Hoizame** [comment]
Hey please update your AtlasLoot :)
