### ISSUE TITLE
Share localized information ?

### ISSUE THREAD

**Issue by Warkdev** [Hoizame/AtlasLootClassic#75]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Hello, I was wondering whether you would allow me to re-use the localization effort that you made for this add-on: https://www.curseforge.com/wow/addons/best-in-slot-classic.

I'd provide back credit of course :)

**Additional context**

None.

**Comment by Hoizame** [comment]
Hey, as all the translations come from the community feel free too reuse them :)

**Comment by Warkdev** [comment]
Awesome, you would save me a lot of work!
