### ISSUE TITLE
Add Sandarr Dunereaver (ZF) to the loot table

### ISSUE THREAD

**Issue by woopydalan** [Hoizame/AtlasLootClassic#77]
The rare boss in ZF, Sandarr Dunereaver, is not in the boss list. Can you add him? He is a rare boss.

https://classic.wowhead.com/npc=10080/sandarr-dunereaver

**Comment by Hoizame** [comment]
Hi thanks. I will add the boss on the weekend :)

**Comment by woopydalan** [comment]
@Hoizame Awesome, when you do can you give me a minute to update all the localization before you publish it on curseforge as a non-alfa/beta version?

**Comment by Hoizame** [comment]
Hey a alpha is out with the boss.

**Comment by woopydalan** [comment]
Thanks, I already updated all the localization

**Comment by Hoizame** [comment]
Thanks :)
