### ISSUE TITLE
Sunken Temple Level Range

### ISSUE THREAD

**Issue by woopydalan** [Hoizame/AtlasLootClassic#80]
Hi,

The addon says the level range is 50-56, but the meeting stone gives the level range at 50-60. I don't know what you are using to determine your level ranges for dungeons.

**Comment by Hoizame** [comment]
hmm can't remember where I get them but I updated the level ranges now

**Comment by woopydalan** [comment]
@Hoizame Hi, with that update you changed all the level ranges. The other ranges looked good. The ranges you had (except sunken temple) were from the meeting stone level range. I'm guessing you changed to use the Atlas level range. Now ST is inconsistent with the other ones. Not sure how you want to proceed with that.
