### ISSUE TITLE
Missing Boss level

### ISSUE THREAD

**Issue by daberniegithub** [Hoizame/AtlasLootClassic#85]
I used to see the level of the Bosses next to their names but that is gone.
The changelog shows an option to show or hide the level but there is no option visible.

**Comment by daberniegithub** [comment]
checked SavedVariables file and found : ["enableBossLevel"] = true,
still it does not show ingame

**Comment by daberniegithub** [comment]
searched all .lua files in the folder and found ["enableBossLevel"] = false, in db.lua.
changed it to true and it works ingame
any way to change it ingame i overlook ?

**Comment by Hoizame** [comment]
hmmm it should be there 
![image](https://user-images.githubusercontent.com/45636893/79641950-00b50a00-819b-11ea-8f91-469342aa6b01.png)
If not what WoW language you are using?

**Comment by daberniegithub** [comment]
how do i open this settings window ? there is no button or keybinding for it !

**Comment by Hoizame** [comment]
Shift+Click on Minimap icon or with "/al options"

**Comment by daberniegithub** [comment]
Great! Would you please mention it on the curseforge addon page ?
Would have saved me an hour time searching and trying.
Thank you for your work and response.

**Comment by Hoizame** [comment]
Maybe no bad idea, its added :D
