### ISSUE TITLE
Tome of Polymorph: Turtle available in P4

### ISSUE THREAD

**Issue by Djfe** [Hoizame/AtlasLootClassic#86]
**Module:**?
**Category:**tomb?
**Loottable:**Zul'Gurub Gahz'ranka
**Items:**
https://classic.wowhead.com/item=22739/tome-of-polymorph-turtle#english-comments

It's available in P4. (unlike vanilla WoW or what WoWhead says about it)
On Everlook there are 2 ones available on the AH at the moment.

![https://i.imgur.com/4F919rr.png](https://i.imgur.com/4F919rr.png)

**Comment by Hoizame** [comment]
Danke, ist geändert

**Comment by MisterTooh** [comment]
Agreed! Many of the items appearing as only available in Phase 6 in Atlas Loot are actually available and dropping in Zul'Gurub.

Primal Hakkari Idol

Items Appearing in Shared Loot list.

**Comment by Steinras** [comment]
When can we expect a fix for items in ZG incorrectly marked as phase 6 items?
