### ISSUE TITLE
Random enchant

### ISSUE THREAD

**Issue by psychazia** [Hoizame/AtlasLootClassic#87]
**Is your feature request related to a problem? Please describe.**
When you check loot for a random enchant piece, like for exemple, Abyssal Cloth Amice (in Collections/Silithus Abyssal), it only says that it's 72 armor cloth / <random enchantment>/ +1% hit

**Describe the solution you'd like**
It would be nice that it shows the possibles random enchants like on wowhead : https://classic.wowhead.com/item=20686/abyssal-cloth-amice
I don't know how, perhaps like quest item when you have different turn in possibilities..

**Additional context**

**Comment by Hoizame** [comment]
I have some ideas for that and try to implement it :)
