### ISSUE TITLE
a bunch of little things

### ISSUE THREAD

**Issue by Nihlo** [Hoizame/AtlasLootClassic#88]
A bunch of small fixes:

In general sometimes the text of an item is missing but the icon and the tooltip is there. Reappears if you reload the boss. Looks like this:
https://ibb.co/NsNdTR7

Factions:
Hydraxian Waterlords:
The patterns at revered are not from the Hydraxians but can be learned at Light's Hope Chapel. So those should be moved to Argent Dawn and a bunch of other Recipes which are coming in P6. Hydraxians only give the Quintessences and the Eternal Quintessence is missing at Rev.

Circle of Cenarius:
The Items you can get there by farming several tokes in dailies are missing. Can find those in Battlegear-Quests:  https://classic.wowhead.com/search?q=battlegear#quests
That's P5 too. 

ZG:
- Blood Scythe  doesn't drop of trash but Piles only, can remove it there
- Savage Guard should be P5 and not P6, between aq and naxx (can't know for sure now though ofc)
- at Hakkar: Seafury Gauntlets are Horde only and Peacekeeper Gauntlets are Alliance only, maybe  you can mark that someway
- Primal Hakkari Idols are 100% loot of Mandokir and Jin'do

AQ20:
- the General Rajaxx Encounter has several waves with 7 mini-bosses which have loot aswell. This is missing completly atm. Can check those Captains, Majors and their loot here:
https://classic.wowhead.com/npc=15341/general-rajaxx  (Rajaxx Army box)
- AQ-Opening is hidden in AQ40 and AQ20, Collections would be better
- the boss order is a little bit weird. Usual way is Kuri -> Rajaxx -> Buru -> Moam -> Ossi -> Aya
- trash is missing "Large Obsidian Shard" & "Small Obsidian Shard" which you can mine in AQ20&AQ40. 
- Coif of Elemental Fury is Horde only, Helm of the Holy Avenger is Ally only
- Buru: Slimy Scaled Gauntlets are Horde only, Gloves of the Swarm Ally only
- Ossirian: Runic Stone Shoulders -> Horde. Mantle of Horusath ->Ally

AQ40:
Bug trio has different loot depending on the order you kill them. Maybe there is way to clear this up a little in the Lootframe, like Bug killed last above the colum or something. 

UBRS is technically a raid instances, listed under Dungeons

Stratholme:
- Hearthsinger Forrester is technically no rare, he is always there. Location varies.

Collections:

Legendaries:
Can add that  https://classic.wowhead.com/item=17782/talisman-of-binding-shard
at unobtainable. Was removed from the game but some players got it.

Festivals:
Can remove all those phase tags there. Like Lunar dresses, Love is in the air and Midsummer.

Darkmoon Faire:
a bunch of minor items are missing there, check:
https://classic.wowhead.com/item=19182/darkmoon-faire-prize-ticket#objective-of
while the "Schematic: Steam Tonk Controller" isn't ingame yet, Phase 5 or 6.

Abyssal Invasion:
the order of the bosses is wrong. Templars -> Dukes -> Lords (minor -> major)

PvP
a bunch of minor items are missing, like potions, tabards and standards. Check those two npcs:
https://classic.wowhead.com/npc=12793/brave-stonehide#sells
https://classic.wowhead.com/npc=12781/master-sergeant-biggins#sells

Crafting:
could add the specs of leatherworking, engineering and blacksmithing

Cooking:
- can move Goldthorn Tea to Specials cause it actually restores Mana instead of HP like everything else. 
- Thistle Tea is usable and craftable Rogue only, can't be learned anymore by other classes.

**Comment by Hoizame** [comment]
Wow I take a look at that this weekend thanks!

**Comment by Nihlo** [comment]
kein Ding, sag wenn irgendwas unklar is

**Comment by wallrik** [comment]
> UBRS is technically a raid instances, listed under Dungeons

I really oppose moving UBRS to raids. It is not "technically" a raid. It can be done in a 5 man group. It does not require a raid group to enter the instance.

With that logic, then all the other dungeons that can technically be done in a raid are also raids.
https://classic.wowhead.com/news=294592/player-caps-for-classic-wow-dungeons
