### ISSUE TITLE
Mageweave Bags. (Missing Red Training Skill.)

### ISSUE THREAD

**Issue by Zeuaireus** [Hoizame/AtlasLootClassic#9]
**Module:**
Crafting -> Tailoring -> Bag.

**Category:**
Crafting. 

**Loottable:**
https://classic.wowhead.com/item=10050/mageweave-bag
https://classic.wowhead.com/item=10051/red-mageweave-bag

**Items:**
Item ID# 10050
Item ID# 10051

**Additional context**

Hi. According to AtlasLootClassic-v1.1.8-beta-classic, training for Mageweave Bags starts at Tailoring 240. But Classic wowhead is showing the normal Mageweave bag starts at 225 and the red one starts at 235 from the recipe. Currently these two numbers are missing from the current release of the addon.

Sources: 
https://classic.wowhead.com/item=10050/mageweave-bag
https://classic.wowhead.com/item=10051/red-mageweave-bag

**Comment by Hoizame** [comment]
Thanks! fixed for next version.
Think I have to do more fixes of the start level from tailoring :D
