### ISSUE TITLE
Seperate Strat bosses in Live and UD

### ISSUE THREAD

**Issue by jmaslows** [Hoizame/AtlasLootClassic#99]
It's hard to tell which bosses are in each dungeon since they are all slammed in strathholme.  It would be helpful if they were seperated.

**Comment by Hoizame** [comment]
Hm i dont like the Idea of splitting the complete dungeon but maybe colorize the names would be a thing?
![image](https://user-images.githubusercontent.com/45636893/91072801-55c9c680-e63a-11ea-92ac-14f74d77b1e4.png)
